// SixRoll - a "roll six random letters, discover words and patterns" leaderboard game
// Inspired by RNGdle's number-pattern badge system, applied to letters instead of digits.

const WORD_LIST = ["AAA", "AARON", "ABC", "ABLE", "ABOUT", "ABOVE", "ABROAD", "ABS", "ABSENT", "ABU", "ABUSE", "ACC", "ACCENT", "ACCEPT", "ACCESS", "ACE", "ACER", "ACID", "ACIDS", "ACM", "ACNE", "ACRE", "ACRES", "ACROSS", "ACT", "ACTING", "ACTION", "ACTIVE", "ACTOR", "ACTORS", "ACTS", "ACTUAL", "ACUTE", "ADA", "ADAM", "ADAMS", "ADD", "ADDED", "ADDING", "ADDS", "ADIDAS", "ADIPEX", "ADJUST", "ADMIN", "ADMIT", "ADOBE", "ADOPT", "ADRIAN", "ADS", "ADSL", "ADULT", "ADULTS", "ADVERT", "ADVICE", "ADVISE", "ADWARE", "AERIAL", "AFFAIR", "AFFECT", "AFFORD", "AFRAID", "AFRICA", "AFTER", "AGAIN", "AGE", "AGED", "AGENCY", "AGENDA", "AGENT", "AGENTS", "AGES", "AGING", "AGO", "AGREE", "AGREED", "AGREES", "AHEAD", "AID", "AIDS", "AIM", "AIMED", "AIMS", "AIR", "AKA", "ALA", "ALAN", "ALARM", "ALASKA", "ALBANY", "ALBERT", "ALBUM", "ALBUMS", "ALERT", "ALERTS", "ALEX", "ALFRED", "ALI", "ALIAS", "ALICE", "ALIEN", "ALIGN", "ALIKE", "ALIVE", "ALL", "ALLAH", "ALLAN", "ALLEN", "ALLIED", "ALLOW", "ALLOWS", "ALLOY", "ALMOST", "ALONE", "ALONG", "ALOT", "ALPHA", "ALPINE", "ALSO", "ALT", "ALTER", "ALTO", "ALUMNI", "ALWAYS", "AMANDA", "AMAZON", "AMBER", "AMBIEN", "AMD", "AMEND", "AMINO", "AMONG", "AMOUNT", "AMP", "AMY", "ANA", "ANALOG", "ANCHOR", "AND", "ANDALE", "ANDREA", "ANDREW", "ANDY", "ANGEL", "ANGELA", "ANGELS", "ANGER", "ANGLE", "ANGOLA", "ANGRY", "ANIMAL", "ANIME", "ANN", "ANNA", "ANNE", "ANNEX", "ANNIE", "ANNUAL", "ANSWER", "ANT", "ANTI", "ANY", "ANYONE", "ANYWAY", "AOL", "APACHE", "APART", "API", "APNIC", "APOLLO", "APP", "APPEAL", "APPEAR", "APPLE", "APPLY", "APPROX", "APPS", "APR", "APRIL", "APT", "AQUA", "ARAB", "ARABIA", "ARABIC", "ARBOR", "ARC", "ARCADE", "ARCH", "ARCTIC", "ARE", "AREA", "AREAS", "ARENA", "ARG", "ARGUE", "ARGUED", "ARISE", "ARM", "ARMED", "ARMOR", "ARMS", "ARMY", "ARNOLD", "AROUND", "ARRAY", "ARREST", "ARRIVE", "ARROW", "ART", "ARTHUR", "ARTIST", "ARTS", "ARUBA", "ASCII", "ASH", "ASHLEY", "ASIA", "ASIAN", "ASIDE", "ASIN", "ASK", "ASKED", "ASKING", "ASKS", "ASN", "ASP", "ASPECT", "ASSESS", "ASSET", "ASSETS", "ASSIGN", "ASSIST", "ASSUME", "ASSURE", "ASTHMA", "ASUS", "ASYLUM", "ATA", "ATE", "ATHENS", "ATI", "ATLAS", "ATM", "ATOM", "ATOMIC", "ATTACH", "ATTACK", "ATTEND", "AUBURN", "AUD", "AUDI", "AUDIO", "AUDIT", "AUG", "AUGUST", "AURORA", "AUS", "AUSTIN", "AUTHOR", "AUTO", "AUTOS", "AUTUMN", "AVATAR", "AVE", "AVENUE", "AVG", "AVI", "AVOID", "AVON", "AWARD", "AWARDS", "AWARE", "AWAY", "AWFUL", "AXIS", "AYE", "BABE", "BABES", "BABIES", "BABY", "BACK", "BACKED", "BACKUP", "BACON", "BAD", "BADGE", "BADLY", "BAG", "BAGS", "BAILEY", "BAKER", "BAKING", "BALD", "BALI", "BALL", "BALLET", "BALLOT", "BAN", "BANANA", "BAND", "BANDS", "BANG", "BANK", "BANKS", "BANNED", "BANNER", "BAR", "BARBIE", "BARE", "BARELY", "BARN", "BARNES", "BARREL", "BARRY", "BARS", "BASE", "BASED", "BASES", "BASIC", "BASICS", "BASIN", "BASIS", "BASKET", "BASS", "BAT", "BATCH", "BATH", "BATHS", "BATMAN", "BATTLE", "BAY", "BBC", "BBS", "BEACH", "BEADS", "BEAM", "BEAN", "BEANS", "BEAR", "BEARS", "BEAST", "BEAT", "BEATS", "BEAUTY", "BEAVER", "BECAME", "BECOME", "BED", "BEDS", "BEE", "BEEF", "BEEN", "BEER", "BEFORE", "BEGAN", "BEGIN", "BEGINS", "BEGUN", "BEHALF", "BEHIND", "BEING", "BEINGS", "BELIEF", "BELIZE", "BELKIN", "BELL", "BELLE", "BELLY", "BELONG", "BELOW", "BELT", "BELTS", "BEN", "BENCH", "BEND", "BENT", "BENZ", "BERLIN", "BERRY", "BESIDE", "BEST", "BET", "BETA", "BETH", "BETTER", "BETTY", "BEYOND", "BHUTAN", "BIAS", "BIBLE", "BID", "BIDDER", "BIDS", "BIG", "BIGGER", "BIKE", "BIKES", "BIKINI", "BILL", "BILLS", "BILLY", "BIN", "BINARY", "BIND", "BINGO", "BIO", "BIOL", "BIOS", "BIRD", "BIRDS", "BIRTH", "BISHOP", "BIT", "BITE", "BITS", "BIZ", "BLACK", "BLACKS", "BLADE", "BLADES", "BLAH", "BLAIR", "BLAKE", "BLAME", "BLANK", "BLAST", "BLEND", "BLESS", "BLIND", "BLINK", "BLOCK", "BLOCKS", "BLOG", "BLOGS", "BLOND", "BLONDE", "BLOOD", "BLOOM", "BLOW", "BLUE", "BLUES", "BLVD", "BMW", "BOARD", "BOARDS", "BOAT", "BOATS", "BOB", "BOBBY", "BOC", "BODIES", "BODY", "BOLD", "BOLT", "BOMB", "BON", "BOND", "BONDS", "BONE", "BONES", "BONUS", "BOOK", "BOOKS", "BOOL", "BOOM", "BOOST", "BOOT", "BOOTH", "BOOTS", "BOOTY", "BORDER", "BORED", "BORING", "BORN", "BOSNIA", "BOSS", "BOSTON", "BOTH", "BOTHER", "BOTTLE", "BOTTOM", "BOUGHT", "BOUND", "BOW", "BOWL", "BOX", "BOXED", "BOXES", "BOXING", "BOY", "BOYS", "BRA", "BRAD", "BRAIN", "BRAKE", "BRAKES", "BRANCH", "BRAND", "BRANDS", "BRAS", "BRASS", "BRAVE", "BRAZIL", "BREACH", "BREAD", "BREAK", "BREAKS", "BREAST", "BREATH", "BREED", "BREEDS", "BRIAN", "BRICK", "BRIDAL", "BRIDE", "BRIDGE", "BRIEF", "BRIEFS", "BRIGHT", "BRING", "BRINGS", "BROAD", "BROKE", "BROKEN", "BROKER", "BRONZE", "BROOK", "BROOKS", "BROWN", "BROWSE", "BRUCE", "BRUNEI", "BRUSH", "BRUTAL", "BRYAN", "BRYANT", "BUBBLE", "BUCK", "BUCKS", "BUDDY", "BUDGET", "BUF", "BUFFER", "BUFING", "BUG", "BUGS", "BUILD", "BUILDS", "BUILT", "BULK", "BULL", "BULLET", "BUMPER", "BUNCH", "BUNDLE", "BUNNY", "BURDEN", "BUREAU", "BURIED", "BURKE", "BURN", "BURNER", "BURNS", "BURST", "BURTON", "BUS", "BUSES", "BUSH", "BUSY", "BUT", "BUTLER", "BUTTER", "BUTTON", "BUTTS", "BUY", "BUYER", "BUYERS", "BUYING", "BUYS", "BUZZ", "BYE", "BYTE", "BYTES", "CAB", "CABIN", "CABLE", "CABLES", "CACHE", "CACHED", "CAD", "CAFE", "CAGE", "CAKE", "CAKES", "CAL", "CALL", "CALLED", "CALLS", "CALM", "CALVIN", "CAM", "CAME", "CAMEL", "CAMERA", "CAMP", "CAMPS", "CAMPUS", "CAMS", "CAN", "CANADA", "CANAL", "CANCEL", "CANCER", "CANDLE", "CANDY", "CANNON", "CANON", "CANT", "CANVAS", "CANYON", "CAP", "CAPE", "CAPS", "CAR", "CARB", "CARBON", "CARD", "CARDS", "CARE", "CAREER", "CAREY", "CARGO", "CARING", "CARL", "CARLO", "CARLOS", "CARMEN", "CAROL", "CARPET", "CARRY", "CARS", "CART", "CARTER", "CAS", "CASA", "CASE", "CASES", "CASEY", "CASH", "CASINO", "CASIO", "CAST", "CASTLE", "CASUAL", "CAT", "CATCH", "CATS", "CATTLE", "CAUGHT", "CAUSE", "CAUSED", "CAUSES", "CAVE", "CAYMAN", "CBS", "CCD", "CDNA", "CDS", "CDT", "CEDAR", "CELEBS", "CELL", "CELLS", "CELTIC", "CEMENT", "CENSUS", "CENT", "CENTER", "CENTRE", "CENTS", "CEO", "CET", "CFR", "CGI", "CHAD", "CHAIN", "CHAINS", "CHAIR", "CHAIRS", "CHAN", "CHANCE", "CHANGE", "CHAOS", "CHAPEL", "CHAR", "CHARGE", "CHARM", "CHARMS", "CHART", "CHARTS", "CHASE", "CHAT", "CHEAP", "CHEAT", "CHEATS", "CHECK", "CHECKS", "CHEERS", "CHEESE", "CHEF", "CHEM", "CHEN", "CHEQUE", "CHERRY", "CHESS", "CHEST", "CHEVY", "CHI", "CHICK", "CHICKS", "CHIEF", "CHILD", "CHILE", "CHINA", "CHIP", "CHIPS", "CHO", "CHOICE", "CHOIR", "CHOOSE", "CHORUS", "CHOSE", "CHOSEN", "CHRIS", "CHRIST", "CHROME", "CHUBBY", "CHUCK", "CHURCH", "CIA", "CIALIS", "CIAO", "CINDY", "CINEMA", "CIO", "CIR", "CIRCLE", "CIRCUS", "CISCO", "CITE", "CITED", "CITIES", "CITY", "CIVIC", "CIVIL", "CLAIM", "CLAIMS", "CLAIRE", "CLAN", "CLARA", "CLARK", "CLARKE", "CLASS", "CLAUSE", "CLAY", "CLEAN", "CLEAR", "CLERK", "CLICK", "CLICKS", "CLIENT", "CLIFF", "CLIMB", "CLINIC", "CLIP", "CLIPS", "CLOCK", "CLOCKS", "CLONE", "CLOSE", "CLOSED", "CLOSER", "CLOSES", "CLOTH", "CLOUD", "CLOUDS", "CLOUDY", "CLUB", "CLUBS", "CMS", "CNET", "CNN", "COACH", "COAL", "COAST", "COAT", "COATED", "COD", "CODE", "CODES", "CODING", "COFFEE", "COHEN", "COIN", "COINS", "COL", "COLD", "COLE", "COLIN", "COLLAR", "COLON", "COLONY", "COLOR", "COLORS", "COLOUR", "COLUMN", "COM", "COMBAT", "COMBO", "COME", "COMEDY", "COMES", "COMIC", "COMICS", "COMING", "COMM", "COMMIT", "COMMON", "COMP", "COMPAQ", "COMPLY", "CON", "CONDO", "CONDOS", "CONF", "CONFIG", "CONGO", "CONS", "CONST", "COOK", "COOKED", "COOKIE", "COOL", "COOLER", "COOPER", "COP", "COPE", "COPIED", "COPIES", "COPPER", "COPY", "CORAL", "CORD", "CORE", "CORK", "CORN", "CORNER", "CORP", "CORPS", "CORPUS", "COS", "COST", "COSTA", "COSTS", "COTTON", "COULD", "COUNT", "COUNTS", "COUNTY", "COUPLE", "COUPON", "COURSE", "COURT", "COURTS", "COVE", "COVER", "COVERS", "COW", "COWBOY", "CPU", "CRACK", "CRADLE", "CRAFT", "CRAFTS", "CRAIG", "CRAPS", "CRASH", "CRAZY", "CREAM", "CREATE", "CREDIT", "CREEK", "CREST", "CREW", "CRIME", "CRIMES", "CRISIS", "CRM", "CROP", "CROPS", "CROSS", "CROWD", "CROWN", "CRUDE", "CRUISE", "CRUZ", "CRY", "CSS", "CST", "CTRL", "CUBA", "CUBE", "CUBIC", "CULT", "CUP", "CUPS", "CURE", "CURSOR", "CURTIS", "CURVE", "CURVES", "CUSTOM", "CUT", "CUTE", "CUTS", "CVS", "CYBER", "CYCLE", "CYCLES", "CYPRUS", "CZECH", "DAD", "DADDY", "DAILY", "DAIRY", "DAISY", "DAKOTA", "DALE", "DALLAS", "DAM", "DAMAGE", "DAME", "DAN", "DANA", "DANCE", "DANGER", "DANIEL", "DANISH", "DANNY", "DANS", "DARE", "DARK", "DARWIN", "DAS", "DASH", "DAT", "DATA", "DATE", "DATED", "DATES", "DATING", "DAVE", "DAVID", "DAVIS", "DAWN", "DAY", "DAYS", "DAYTON", "DDR", "DEAD", "DEADLY", "DEAF", "DEAL", "DEALER", "DEALS", "DEALT", "DEAN", "DEAR", "DEATH", "DEATHS", "DEBATE", "DEBIAN", "DEBT", "DEBUG", "DEBUT", "DEC", "DECADE", "DECENT", "DECIDE", "DECK", "DECOR", "DEE", "DEEMED", "DEEP", "DEEPER", "DEEPLY", "DEER", "DEF", "DEFEAT", "DEFEND", "DEFINE", "DEGREE", "DEL", "DELAY", "DELAYS", "DELETE", "DELHI", "DELL", "DELTA", "DELUXE", "DEM", "DEMAND", "DEMO", "DEN", "DENIAL", "DENIED", "DENNIS", "DENSE", "DENTAL", "DENVER", "DENY", "DEPEND", "DEPOT", "DEPT", "DEPTH", "DEPUTY", "DER", "DERBY", "DEREK", "DES", "DESERT", "DESIGN", "DESIRE", "DESK", "DETAIL", "DETECT", "DEV", "DEVEL", "DEVICE", "DEVIL", "DEVON", "DIAL", "DIALOG", "DIANA", "DIANE", "DIARY", "DICE", "DICKE", "DID", "DIE", "DIED", "DIEGO", "DIES", "DIESEL", "DIET", "DIFF", "DIFFER", "DIFFS", "DIG", "DIGEST", "DIGIT", "DIM", "DINING", "DINNER", "DIP", "DIR", "DIRECT", "DIRT", "DIRTY", "DIS", "DISC", "DISCO", "DISCS", "DISH", "DISHES", "DISK", "DISKS", "DISNEY", "DIST", "DIV", "DIVE", "DIVIDE", "DIVINE", "DIVING", "DIVX", "DIY", "DNA", "DNS", "DOC", "DOCK", "DOCS", "DOCTOR", "DOD", "DODGE", "DOE", "DOES", "DOG", "DOGS", "DOING", "DOLL", "DOLLAR", "DOLLS", "DOM", "DOMAIN", "DOME", "DON", "DONALD", "DONATE", "DONE", "DONNA", "DONOR", "DONORS", "DONT", "DOOM", "DOOR", "DOORS", "DOS", "DOSAGE", "DOSE", "DOT", "DOUBLE", "DOUBT", "DOUG", "DOVER", "DOW", "DOWN", "DOZEN", "DOZENS", "DPI", "DRAFT", "DRAG", "DRAGON", "DRAIN", "DRAMA", "DRAW", "DRAWN", "DRAWS", "DREAM", "DREAMS", "DRESS", "DREW", "DRIED", "DRILL", "DRINK", "DRINKS", "DRIVE", "DRIVEN", "DRIVER", "DRIVES", "DROP", "DROPS", "DROVE", "DRUG", "DRUGS", "DRUM", "DRUMS", "DRUNK", "DRY", "DRYER", "DSC", "DSL", "DTS", "DUAL", "DUBAI", "DUBLIN", "DUCK", "DUDE", "DUE", "DUI", "DUKE", "DUMB", "DUMP", "DUNCAN", "DUO", "DURHAM", "DURING", "DUST", "DUTCH", "DUTIES", "DUTY", "DVD", "DVDS", "DYING", "DYLAN", "EACH", "EAGLE", "EAGLES", "EAR", "EARL", "EARLY", "EARN", "EARNED", "EARS", "EARTH", "EASE", "EASIER", "EASILY", "EAST", "EASTER", "EASY", "EAT", "EATING", "EAU", "EBAY", "EBONY", "EBOOK", "EBOOKS", "ECHO", "ECO", "EDDIE", "EDEN", "EDGAR", "EDGE", "EDGES", "EDIT", "EDITED", "EDITOR", "EDS", "EDT", "EDWARD", "EFFECT", "EFFORT", "EGG", "EGGS", "EGYPT", "EIGHT", "EITHER", "ELDER", "ELECT", "ELEVEN", "ELITE", "ELLEN", "ELLIS", "ELSE", "ELVIS", "EMACS", "EMAIL", "EMAILS", "EMILY", "EMINEM", "EMMA", "EMPIRE", "EMPLOY", "EMPTY", "ENABLE", "ENB", "END", "ENDED", "ENDIF", "ENDING", "ENDS", "ENEMY", "ENERGY", "ENG", "ENGAGE", "ENGINE", "ENJOY", "ENOUGH", "ENSURE", "ENT", "ENTER", "ENTERS", "ENTIRE", "ENTITY", "ENTRY", "ENZYME", "EOS", "EPA", "EPIC", "EPSON", "EQUAL", "EQUITY", "ERA", "ERIC", "ERIK", "ERP", "ERROR", "ERRORS", "ESCAPE", "ESPN", "ESSAY", "ESSAYS", "ESSEX", "EST", "ESTATE", "ETC", "ETHICS", "ETHNIC", "EUGENE", "EUR", "EURO", "EUROPE", "EUROS", "EVA", "EVAL", "EVANS", "EVE", "EVEN", "EVENT", "EVENTS", "EVER", "EVERY", "EVIL", "EXACT", "EXAM", "EXAMS", "EXCEED", "EXCEL", "EXCEPT", "EXCESS", "EXCUSE", "EXEC", "EXEMPT", "EXIST", "EXISTS", "EXIT", "EXOTIC", "EXP", "EXPAND", "EXPECT", "EXPERT", "EXPO", "EXPORT", "EXT", "EXTEND", "EXTENT", "EXTRA", "EXTRAS", "EYE", "EYED", "EYES", "FABRIC", "FACE", "FACED", "FACES", "FACIAL", "FACING", "FACT", "FACTOR", "FACTS", "FAIL", "FAILED", "FAILS", "FAIR", "FAIRLY", "FAIRY", "FAITH", "FAKE", "FALL", "FALLEN", "FALLS", "FALSE", "FAME", "FAMILY", "FAMOUS", "FAN", "FANCY", "FANS", "FAQ", "FAQS", "FAR", "FARE", "FARES", "FARM", "FARMER", "FARMS", "FAST", "FASTER", "FAT", "FATAL", "FATE", "FATHER", "FATTY", "FAULT", "FAVOR", "FAVORS", "FAVOUR", "FAX", "FBI", "FCC", "FDA", "FEAR", "FEARS", "FEAT", "FEB", "FED", "FEE", "FEED", "FEEDS", "FEEL", "FEELS", "FEES", "FEET", "FELL", "FELLOW", "FELT", "FEMALE", "FENCE", "FEOF", "FERRY", "FETISH", "FEVER", "FEW", "FEWER", "FIBER", "FIBRE", "FIELD", "FIELDS", "FIFTH", "FIFTY", "FIG", "FIGHT", "FIGURE", "FIJI", "FILE", "FILED", "FILES", "FILING", "FILL", "FILLED", "FILM", "FILME", "FILMS", "FILTER", "FIN", "FINAL", "FINALS", "FIND", "FINDER", "FINDS", "FINE", "FINEST", "FINGER", "FINISH", "FINITE", "FIRE", "FIRED", "FIRES", "FIRM", "FIRMS", "FIRST", "FISCAL", "FISH", "FISHER", "FIST", "FIT", "FITS", "FITTED", "FIVE", "FIX", "FIXED", "FIXES", "FLAG", "FLAGS", "FLAME", "FLASH", "FLAT", "FLAVOR", "FLEECE", "FLEET", "FLESH", "FLEX", "FLICKR", "FLIGHT", "FLIP", "FLOAT", "FLOOD", "FLOOR", "FLOORS", "FLOPPY", "FLORAL", "FLOUR", "FLOW", "FLOWER", "FLOWS", "FLOYD", "FLU", "FLUID", "FLUSH", "FLUX", "FLY", "FLYER", "FLYING", "FOAM", "FOCAL", "FOCUS", "FOG", "FOLD", "FOLDER", "FOLK", "FOLKS", "FOLLOW", "FONT", "FONTS", "FOO", "FOOD", "FOODS", "FOOL", "FOOT", "FOR", "FORBES", "FORCE", "FORCED", "FORCES", "FORD", "FOREST", "FORGE", "FORGET", "FORGOT", "FORK", "FORM", "FORMAL", "FORMAT", "FORMED", "FORMER", "FORMS", "FORT", "FORTH", "FORTY", "FORUM", "FORUMS", "FOSSIL", "FOSTER", "FOTO", "FOTOS", "FOUGHT", "FOUL", "FOUND", "FOUR", "FOURTH", "FOX", "FRAME", "FRAMED", "FRAMES", "FRANCE", "FRANK", "FRASER", "FRAUD", "FRED", "FREE", "FREELY", "FREEZE", "FRENCH", "FRESH", "FRI", "FRIDAY", "FRIDGE", "FRIEND", "FROG", "FROM", "FRONT", "FROST", "FROZEN", "FRUIT", "FRUITS", "FTP", "FUEL", "FUJI", "FULL", "FULLY", "FUN", "FUND", "FUNDED", "FUNDS", "FUNK", "FUNKY", "FUNNY", "FUR", "FUSION", "FUTURE", "FUZZY", "FWD", "GAGE", "GAIN", "GAINED", "GAINS", "GALAXY", "GALE", "GAME", "GAMES", "GAMING", "GAMMA", "GANG", "GAP", "GAPS", "GARAGE", "GARCIA", "GARDEN", "GARLIC", "GARMIN", "GARY", "GAS", "GATE", "GATES", "GATHER", "GAUGE", "GAVE", "GAY", "GAYS", "GBA", "GBP", "GCC", "GDP", "GEAR", "GEEK", "GEL", "GEM", "GEN", "GENDER", "GENE", "GENES", "GENEVA", "GENIUS", "GENOME", "GENRE", "GENRES", "GENTLE", "GENTLY", "GEO", "GEORGE", "GERALD", "GERMAN", "GET", "GETS", "GHANA", "GHOST", "GHZ", "GIANT", "GIANTS", "GIBSON", "GIF", "GIFT", "GIFTS", "GIG", "GIRL", "GIRLS", "GIS", "GIVE", "GIVEN", "GIVES", "GIVING", "GLAD", "GLANCE", "GLASS", "GLEN", "GLENN", "GLOBAL", "GLOBE", "GLORY", "GLOVES", "GLOW", "GMBH", "GMC", "GMT", "GNOME", "GNU", "GOAL", "GOALS", "GOAT", "GODS", "GOES", "GOING", "GOLD", "GOLDEN", "GOLF", "GONE", "GONNA", "GOOD", "GOODS", "GOOGLE", "GORDON", "GORE", "GOSPEL", "GOSSIP", "GOT", "GOTHIC", "GOTO", "GOTTA", "GOTTEN", "GPL", "GPS", "GRAB", "GRACE", "GRAD", "GRADE", "GRADES", "GRAHAM", "GRAIN", "GRAMS", "GRAND", "GRANDE", "GRANNY", "GRANT", "GRANTS", "GRAPH", "GRAPHS", "GRAS", "GRASS", "GRATIS", "GRAVE", "GRAY", "GREAT", "GREECE", "GREEK", "GREEN", "GREENE", "GREG", "GREW", "GREY", "GRID", "GRILL", "GRIP", "GROOVE", "GROSS", "GROUND", "GROUP", "GROUPS", "GROVE", "GROW", "GROWN", "GROWS", "GROWTH", "GSM", "GST", "GTK", "GUAM", "GUARD", "GUARDS", "GUESS", "GUEST", "GUESTS", "GUI", "GUIDE", "GUIDED", "GUIDES", "GUILD", "GUILTY", "GUINEA", "GUITAR", "GULF", "GUN", "GUNS", "GURU", "GUY", "GUYANA", "GUYS", "GYM", "GZIP", "HABITS", "HACK", "HACKER", "HAD", "HAIR", "HAIRY", "HAITI", "HALF", "HALL", "HALO", "HAM", "HAMMER", "HAND", "HANDED", "HANDLE", "HANDS", "HANDY", "HANG", "HANS", "HANSEN", "HAPPEN", "HAPPY", "HARBOR", "HARD", "HARDER", "HARDLY", "HARLEY", "HARM", "HAROLD", "HARPER", "HARRIS", "HARRY", "HART", "HARVEY", "HAS", "HASH", "HAT", "HATE", "HATS", "HAVE", "HAVEN", "HAVING", "HAWAII", "HAWK", "HAY", "HAYES", "HAZARD", "HDTV", "HEAD", "HEADED", "HEADER", "HEADS", "HEALTH", "HEAR", "HEARD", "HEART", "HEARTS", "HEAT", "HEATED", "HEATER", "HEATH", "HEAVEN", "HEAVY", "HEBREW", "HEEL", "HEIGHT", "HELD", "HELEN", "HELENA", "HELLO", "HELMET", "HELP", "HELPED", "HELPS", "HENCE", "HENRY", "HER", "HERALD", "HERB", "HERBAL", "HERBS", "HERE", "HEREBY", "HEREIN", "HERO", "HEROES", "HEY", "HIDDEN", "HIDE", "HIGH", "HIGHER", "HIGHLY", "HIGHS", "HIKING", "HILL", "HILLS", "HILTON", "HIM", "HINDU", "HINT", "HINTS", "HIP", "HIRE", "HIRED", "HIRING", "HIS", "HIST", "HIT", "HITS", "HIV", "HOBBY", "HOCKEY", "HOLD", "HOLDEM", "HOLDER", "HOLDS", "HOLE", "HOLES", "HOLLOW", "HOLLY", "HOLMES", "HOLY", "HOME", "HOMES", "HON", "HONDA", "HONEST", "HONEY", "HONG", "HONOR", "HONORS", "HOOD", "HOOK", "HOP", "HOPE", "HOPED", "HOPES", "HOPING", "HORN", "HORROR", "HORSE", "HORSES", "HOSE", "HOST", "HOSTED", "HOSTEL", "HOSTS", "HOT", "HOTEL", "HOTELS", "HOUR", "HOURLY", "HOURS", "HOUSE", "HOUSES", "HOW", "HOWARD", "HOWTO", "HREF", "HRS", "HTML", "HTTP", "HUB", "HUDSON", "HUGE", "HUGH", "HUGHES", "HUGO", "HULL", "HUMAN", "HUMANS", "HUMOR", "HUNG", "HUNGER", "HUNGRY", "HUNT", "HUNTER", "HURT", "HWY", "HYBRID", "IAN", "IBM", "ICE", "ICON", "ICONS", "ICQ", "ICT", "IDAHO", "IDE", "IDEA", "IDEAL", "IDEAS", "IDLE", "IDOL", "IDS", "IEEE", "IGNORE", "III", "ILL", "IMAGE", "IMAGES", "IMG", "IMMUNE", "IMPACT", "IMPORT", "IMPOSE", "INBOX", "INC", "INCH", "INCHES", "INCL", "INCOME", "IND", "INDEED", "INDEX", "INDIA", "INDIAN", "INDIE", "INDOOR", "INF", "INFANT", "INFO", "INFORM", "ING", "INJURY", "INK", "INKJET", "INLINE", "INN", "INNER", "INNS", "INPUT", "INPUTS", "INS", "INSERT", "INSIDE", "INT", "INTAKE", "INTEL", "INTEND", "INTENT", "INTER", "INTL", "INTO", "INTRO", "INVEST", "INVITE", "ION", "IOWA", "IPAQ", "IPOD", "IPS", "IRA", "IRAN", "IRAQ", "IRAQI", "IRC", "IRISH", "IRON", "IRS", "ISA", "ISAAC", "ISBN", "ISLAM", "ISLAND", "ISLE", "ISO", "ISP", "ISRAEL", "ISSN", "ISSUE", "ISSUED", "ISSUES", "IST", "ITALIA", "ITALIC", "ITALY", "ITEM", "ITEMS", "ITS", "ITSELF", "ITUNES", "IVORY", "JACK", "JACKET", "JACKIE", "JACOB", "JADE", "JAGUAR", "JAIL", "JAKE", "JAM", "JAMES", "JAMIE", "JAN", "JANE", "JANET", "JAPAN", "JAR", "JASON", "JAVA", "JAY", "JAZZ", "JEAN", "JEANS", "JEEP", "JEFF", "JENNY", "JEREMY", "JERRY", "JERSEY", "JESSE", "JESUS", "JET", "JETS", "JEWEL", "JEWISH", "JEWS", "JILL", "JIM", "JIMMY", "JOAN", "JOB", "JOBS", "JOE", "JOEL", "JOHN", "JOHNNY", "JOHNS", "JOIN", "JOINED", "JOINS", "JOINT", "JOKE", "JOKES", "JON", "JONES", "JORDAN", "JOSE", "JOSEPH", "JOSH", "JOSHUA", "JOY", "JOYCE", "JPEG", "JPG", "JUAN", "JUDGE", "JUDGES", "JUDY", "JUICE", "JUL", "JULIA", "JULIAN", "JULIE", "JULY", "JUMP", "JUN", "JUNE", "JUNGLE", "JUNIOR", "JUNK", "JURY", "JUST", "JUSTIN", "JVC", "KAI", "KANSAS", "KAREN", "KARL", "KARMA", "KATE", "KATHY", "KATIE", "KAY", "KDE", "KEEN", "KEEP", "KEEPS", "KEITH", "KELKOO", "KELLY", "KEN", "KENNY", "KENO", "KENT", "KENYA", "KEPT", "KERNEL", "KERRY", "KEVIN", "KEY", "KEYS", "KICK", "KID", "KIDNEY", "KIDS", "KIJIJI", "KILL", "KILLED", "KILLER", "KILLS", "KIM", "KINASE", "KIND", "KINDA", "KINDS", "KING", "KINGS", "KIRK", "KISS", "KIT", "KITS", "KITTY", "KLEIN", "KNEE", "KNEW", "KNIFE", "KNIGHT", "KNIT", "KNIVES", "KNOCK", "KNOW", "KNOWN", "KNOWS", "KODAK", "KONG", "KOREA", "KOREAN", "KRUGER", "KURT", "KUWAIT", "KYLE", "LAB", "LABEL", "LABELS", "LABOR", "LABOUR", "LABS", "LACE", "LACK", "LADDER", "LADEN", "LADIES", "LADY", "LAID", "LAKE", "LAKES", "LAMB", "LAMBDA", "LAMP", "LAMPS", "LAN", "LANCE", "LAND", "LANDS", "LANE", "LANES", "LANG", "LANKA", "LAOS", "LAP", "LAPTOP", "LARGE", "LARGER", "LARRY", "LAS", "LASER", "LAST", "LAT", "LATE", "LATELY", "LATER", "LATEST", "LATEX", "LATIN", "LATINA", "LATINO", "LATTER", "LATVIA", "LAUGH", "LAUNCH", "LAURA", "LAUREN", "LAW", "LAWN", "LAWS", "LAWYER", "LAY", "LAYER", "LAYERS", "LAYOUT", "LAZY", "LBS", "LCD", "LEAD", "LEADER", "LEADS", "LEAF", "LEAGUE", "LEAN", "LEARN", "LEASE", "LEAST", "LEAVE", "LEAVES", "LED", "LEE", "LEEDS", "LEFT", "LEG", "LEGACY", "LEGAL", "LEGEND", "LEGS", "LEMON", "LEN", "LENDER", "LENGTH", "LENS", "LENSES", "LEO", "LEON", "LEONE", "LES", "LESLIE", "LESS", "LESSER", "LESSON", "LET", "LETS", "LETTER", "LEU", "LEVEL", "LEVELS", "LEVY", "LEWIS", "LEXUS", "LIABLE", "LIB", "LIBS", "LID", "LIE", "LIES", "LIFE", "LIFT", "LIGHT", "LIGHTS", "LIKE", "LIKED", "LIKELY", "LIKES", "LIL", "LIME", "LIMIT", "LIMITS", "LINDA", "LINE", "LINEAR", "LINED", "LINES", "LINK", "LINKED", "LINKS", "LINUX", "LION", "LIONS", "LIP", "LIPS", "LIQUID", "LISA", "LIST", "LISTED", "LISTEN", "LISTS", "LIT", "LITE", "LITTLE", "LIVE", "LIVED", "LIVER", "LIVES", "LIVING", "LIZ", "LLC", "LLOYD", "LLP", "LOAD", "LOADED", "LOADS", "LOAN", "LOANS", "LOBBY", "LOC", "LOCAL", "LOCALE", "LOCATE", "LOCK", "LOCKED", "LOCKS", "LODGE", "LOG", "LOGAN", "LOGGED", "LOGIC", "LOGIN", "LOGO", "LOGOS", "LOGS", "LOL", "LONDON", "LONE", "LONELY", "LONG", "LONGER", "LOOK", "LOOKED", "LOOKS", "LOOKUP", "LOOP", "LOOPS", "LOOSE", "LOPEZ", "LORD", "LOS", "LOSE", "LOSING", "LOSS", "LOSSES", "LOST", "LOT", "LOTS", "LOTUS", "LOU", "LOUD", "LOUIS", "LOUISE", "LOUNGE", "LOVE", "LOVED", "LOVELY", "LOVER", "LOVERS", "LOVES", "LOVING", "LOW", "LOWER", "LOWEST", "LOWS", "LTD", "LUCAS", "LUCIA", "LUCK", "LUCKY", "LUCY", "LUIS", "LUKE", "LUNCH", "LUNG", "LUTHER", "LUXURY", "LYCOS", "LYING", "LYNN", "LYRIC", "LYRICS", "MAC", "MACRO", "MAD", "MADE", "MADRID", "MAE", "MAG", "MAGIC", "MAGNET", "MAI", "MAIDEN", "MAIL", "MAILED", "MAILS", "MAILTO", "MAIN", "MAINE", "MAINLY", "MAJOR", "MAKE", "MAKER", "MAKERS", "MAKES", "MAKEUP", "MAKING", "MALAWI", "MALE", "MALES", "MALI", "MALL", "MALTA", "MAMBO", "MAN", "MANAGE", "MANGA", "MANNER", "MANOR", "MANUAL", "MANY", "MAP", "MAPLE", "MAPS", "MAR", "MARBLE", "MARC", "MARCH", "MARCO", "MARCUS", "MARDI", "MARGIN", "MARIA", "MARIAH", "MARIE", "MARINA", "MARINE", "MARIO", "MARION", "MARK", "MARKED", "MARKER", "MARKET", "MARKS", "MARS", "MARSH", "MART", "MARTHA", "MARTIN", "MARVEL", "MARY", "MAS", "MASK", "MASON", "MASS", "MASTER", "MAT", "MATCH", "MATE", "MATH", "MATING", "MATRIX", "MATS", "MATT", "MATTER", "MATURE", "MAUI", "MAX", "MAY", "MAYBE", "MAYOR", "MAZDA", "MBA", "MEAL", "MEALS", "MEAN", "MEANS", "MEANT", "MEAT", "MED", "MEDAL", "MEDIA", "MEDIAN", "MEDIUM", "MEET", "MEETS", "MEETUP", "MEGA", "MEL", "MEM", "MEMBER", "MEMO", "MEMORY", "MEN", "MENS", "MENT", "MENTAL", "MENTOR", "MENU", "MENUS", "MERCY", "MERE", "MERELY", "MERGE", "MERGER", "MERIT", "MERRY", "MESA", "MESH", "MESS", "MET", "META", "METAL", "METALS", "METER", "METERS", "METHOD", "METRES", "METRIC", "METRO", "MEXICO", "MEYER", "MHZ", "MIA", "MIAMI", "MIC", "MICE", "MICHEL", "MICRO", "MID", "MIDDLE", "MIDI", "MIGHT", "MIGHTY", "MIKE", "MIL", "MILAN", "MILD", "MILE", "MILES", "MILK", "MILL", "MILLER", "MILLS", "MILTON", "MIME", "MIN", "MIND", "MINDS", "MINE", "MINES", "MINI", "MINING", "MINOR", "MINS", "MINT", "MINUS", "MINUTE", "MIRROR", "MISC", "MISS", "MISSED", "MIT", "MIX", "MIXED", "MIXER", "MIXING", "MLB", "MLS", "MOBILE", "MOD", "MODE", "MODEL", "MODELS", "MODEM", "MODEMS", "MODERN", "MODES", "MODIFY", "MODS", "MODULE", "MOLD", "MOM", "MOMENT", "MOMS", "MON", "MONACO", "MONDAY", "MONEY", "MONICA", "MONKEY", "MONO", "MONROE", "MONTE", "MONTH", "MONTHS", "MOOD", "MOON", "MOORE", "MORAL", "MORE", "MORGAN", "MORRIS", "MOSCOW", "MOSES", "MOSS", "MOST", "MOSTLY", "MOTEL", "MOTELS", "MOTHER", "MOTION", "MOTOR", "MOTORS", "MOUNT", "MOUNTS", "MOUSE", "MOUTH", "MOVE", "MOVED", "MOVERS", "MOVES", "MOVIE", "MOVIES", "MOVING", "MPEG", "MPEGS", "MPG", "MPH", "MRNA", "MRS", "MSG", "MSGID", "MSGSTR", "MSIE", "MSN", "MTV", "MUCH", "MUD", "MUG", "MULTI", "MUMBAI", "MUNICH", "MURDER", "MURPHY", "MURRAY", "MUSCLE", "MUSEUM", "MUSIC", "MUSLIM", "MUST", "MUTUAL", "MUZE", "MYERS", "MYRTLE", "MYSELF", "MYSQL", "MYTH", "NAIL", "NAILS", "NAKED", "NAM", "NAME", "NAMED", "NAMELY", "NAMES", "NANCY", "NANO", "NAPLES", "NARROW", "NASA", "NASCAR", "NASDAQ", "NASTY", "NAT", "NATHAN", "NATION", "NATIVE", "NATO", "NATURE", "NAV", "NAVAL", "NAVY", "NBA", "NBC", "NCAA", "NEAR", "NEARBY", "NEARLY", "NEC", "NECK", "NEED", "NEEDED", "NEEDLE", "NEEDS", "NEIL", "NELSON", "NEO", "NEON", "NEPAL", "NERVE", "NEST", "NESTED", "NET", "NEURAL", "NEVADA", "NEVER", "NEW", "NEWARK", "NEWBIE", "NEWER", "NEWEST", "NEWLY", "NEWMAN", "NEWS", "NEWTON", "NEXT", "NEXTEL", "NFL", "NHL", "NHS", "NICE", "NICK", "NICKEL", "NICOLE", "NIGER", "NIGHT", "NIGHTS", "NIKE", "NIKON", "NIL", "NINE", "NISSAN", "NOBLE", "NOBODY", "NODE", "NODES", "NOISE", "NOKIA", "NON", "NONE", "NOON", "NOR", "NORM", "NORMAL", "NORMAN", "NORTH", "NORTON", "NORWAY", "NOSE", "NOT", "NOTE", "NOTED", "NOTES", "NOTICE", "NOTIFY", "NOTION", "NOTRE", "NOV", "NOVA", "NOVEL", "NOVELS", "NOW", "NSW", "NTSC", "NUDIST", "NUKE", "NULL", "NUMBER", "NURSE", "NURSES", "NUT", "NUTS", "NUTTEN", "NVIDIA", "NYC", "NYLON", "OAK", "OAKS", "OASIS", "OBJ", "OBJECT", "OBTAIN", "OCCUR", "OCCURS", "OCEAN", "OCLC", "OCT", "ODD", "ODDS", "OECD", "OEM", "OFF", "OFFER", "OFFERS", "OFFICE", "OFFSET", "OFTEN", "OHIO", "OIL", "OILS", "OKAY", "OLD", "OLDER", "OLDEST", "OLIVE", "OLIVER", "OMAHA", "OMAN", "OMEGA", "ONCE", "ONE", "ONES", "ONION", "ONLINE", "ONLY", "ONS", "ONTO", "OOO", "OOPS", "OPEN", "OPENED", "OPENS", "OPERA", "OPT", "OPTICS", "OPTION", "ORACLE", "ORAL", "ORANGE", "ORBIT", "ORDER", "ORDERS", "OREGON", "ORG", "ORGAN", "ORIGIN", "OSCAR", "OTHER", "OTHERS", "OTTAWA", "OUGHT", "OUR", "OURS", "OUT", "OUTER", "OUTLET", "OUTPUT", "OVAL", "OVEN", "OVER", "OWEN", "OWN", "OWNED", "OWNER", "OWNERS", "OWNS", "OXFORD", "OXIDE", "OXYGEN", "OZONE", "PAC", "PACE", "PACK", "PACKED", "PACKET", "PACKS", "PAD", "PADS", "PAGE", "PAGES", "PAID", "PAIN", "PAINT", "PAIR", "PAIRS", "PAL", "PALACE", "PALE", "PALM", "PALMER", "PAM", "PAMELA", "PAN", "PANAMA", "PANEL", "PANELS", "PANIC", "PANTS", "PAPER", "PAPERS", "PAPUA", "PAR", "PARA", "PARADE", "PARCEL", "PARENT", "PARIS", "PARISH", "PARK", "PARKER", "PARKS", "PART", "PARTLY", "PARTS", "PARTY", "PAS", "PASO", "PASS", "PASSED", "PASSES", "PAST", "PASTA", "PASTE", "PASTOR", "PAT", "PATCH", "PATENT", "PATH", "PATHS", "PATIO", "PATROL", "PAUL", "PAXIL", "PAY", "PAYDAY", "PAYING", "PAYPAL", "PAYS", "PCI", "PCS", "PCT", "PDA", "PDAS", "PDF", "PDT", "PEACE", "PEAK", "PEARL", "PEAS", "PEE", "PEEING", "PEER", "PEERS", "PEN", "PENCIL", "PENN", "PENNY", "PENS", "PEOPLE", "PEPPER", "PER", "PERIOD", "PERL", "PERMIT", "PERRY", "PERSON", "PERTH", "PERU", "PEST", "PET", "PETE", "PETER", "PETITE", "PETS", "PGP", "PHASE", "PHASES", "PHD", "PHI", "PHIL", "PHILIP", "PHONE", "PHONES", "PHOTO", "PHOTOS", "PHP", "PHPBB", "PHRASE", "PHYS", "PIANO", "PIC", "PICK", "PICKED", "PICKS", "PICKUP", "PICNIC", "PICS", "PIE", "PIECE", "PIECES", "PIERCE", "PIERRE", "PIG", "PIKE", "PILL", "PILLOW", "PILLS", "PILOT", "PIN", "PINE", "PING", "PINK", "PINS", "PIPE", "PIPES", "PIT", "PITCH", "PIX", "PIXEL", "PIXELS", "PIZZA", "PLACE", "PLACED", "PLACES", "PLAIN", "PLAINS", "PLAN", "PLANE", "PLANES", "PLANET", "PLANS", "PLANT", "PLANTS", "PLASMA", "PLATE", "PLATES", "PLAY", "PLAYED", "PLAYER", "PLAYS", "PLAZA", "PLC", "PLEASE", "PLEDGE", "PLENTY", "PLOT", "PLOTS", "PLUG", "PLUGIN", "PLUS", "PMC", "PMID", "POCKET", "POD", "POEM", "POEMS", "POET", "POETRY", "POINT", "POINTS", "POISON", "POKER", "POLAND", "POLAR", "POLE", "POLICE", "POLICY", "POLISH", "POLL", "POLLS", "POLO", "POLY", "POND", "POOL", "POOLS", "POOR", "POP", "POPE", "POR", "PORK", "PORT", "PORTAL", "PORTER", "PORTS", "POS", "POSE", "POSING", "POST", "POSTAL", "POSTED", "POSTER", "POSTS", "POT", "POTATO", "POTTER", "POUND", "POUNDS", "POUR", "POWDER", "POWELL", "POWER", "POWERS", "PPC", "PPM", "PRAGUE", "PRAISE", "PRAY", "PRAYER", "PRE", "PREFER", "PREFIX", "PREP", "PRESS", "PRETTY", "PREV", "PRICE", "PRICED", "PRICES", "PRIDE", "PRIEST", "PRIME", "PRINCE", "PRINT", "PRINTS", "PRIOR", "PRISON", "PRIX", "PRIZE", "PRIZES", "PRO", "PROBE", "PROC", "PROFIT", "PROMO", "PROMPT", "PROOF", "PROPER", "PROS", "PROT", "PROUD", "PROVE", "PROVED", "PROVEN", "PROXY", "PROZAC", "PSI", "PSP", "PST", "PTS", "PTY", "PUB", "PUBLIC", "PUBMED", "PUBS", "PUERTO", "PULL", "PULLED", "PULSE", "PUMP", "PUMPS", "PUNCH", "PUNK", "PUPILS", "PUPPY", "PURE", "PURPLE", "PURSE", "PURSUE", "PUSH", "PUSHED", "PUT", "PUTS", "PUZZLE", "PVC", "PYTHON", "QATAR", "QLD", "QTY", "QUAD", "QUE", "QUEBEC", "QUEEN", "QUEENS", "QUERY", "QUEST", "QUEUE", "QUI", "QUICK", "QUIET", "QUILT", "QUIT", "QUITE", "QUIZ", "QUOTE", "QUOTED", "QUOTES", "RABBIT", "RACE", "RACES", "RACHEL", "RACIAL", "RACING", "RACK", "RACKS", "RADAR", "RADIO", "RADIOS", "RADIUS", "RAGE", "RAID", "RAIL", "RAIN", "RAISE", "RAISED", "RAISES", "RALLY", "RALPH", "RAM", "RAN", "RANCH", "RAND", "RANDOM", "RANDY", "RANGE", "RANGER", "RANGES", "RANK", "RANKED", "RANKS", "RAP", "RAPID", "RAPIDS", "RARE", "RARELY", "RAT", "RATE", "RATED", "RATES", "RATHER", "RATING", "RATIO", "RATIOS", "RATS", "RAW", "RAY", "RAYS", "RCA", "REACH", "READ", "READER", "READS", "READY", "REAL", "REALLY", "REALM", "REALTY", "REAR", "REASON", "REBATE", "REBEL", "REC", "RECALL", "RECENT", "RECIPE", "RECORD", "RED", "REDEEM", "REDUCE", "REED", "REEF", "REEL", "REF", "REFER", "REFERS", "REFINE", "REFORM", "REFUND", "REFUSE", "REG", "REGARD", "REGGAE", "REGIME", "REGION", "REHAB", "REID", "REJECT", "RELATE", "RELAX", "RELAY", "RELIEF", "RELOAD", "RELY", "REMAIN", "REMARK", "REMEDY", "REMIND", "REMIX", "REMOTE", "REMOVE", "RENDER", "RENEW", "RENO", "RENT", "RENTAL", "REP", "REPAIR", "REPEAT", "REPLY", "REPORT", "RES", "RESCUE", "RESET", "RESIST", "RESORT", "REST", "RESULT", "RESUME", "RETAIL", "RETAIN", "RETRO", "RETURN", "REV", "REVEAL", "REVIEW", "REWARD", "RFC", "RHODE", "RHYTHM", "RIBBON", "RICA", "RICE", "RICH", "RICK", "RICKY", "RICO", "RID", "RIDE", "RIDER", "RIDERS", "RIDES", "RIDGE", "RIDING", "RIGHT", "RIGHTS", "RIM", "RING", "RINGS", "RIO", "RIP", "RIPE", "RISE", "RISING", "RISK", "RISKS", "RIVER", "RIVERS", "RNA", "ROAD", "ROADS", "ROB", "ROBBIE", "ROBERT", "ROBIN", "ROBOT", "ROBOTS", "ROBUST", "ROCK", "ROCKET", "ROCKS", "ROCKY", "ROD", "ROGER", "ROGERS", "ROLAND", "ROLE", "ROLES", "ROLL", "ROLLED", "ROLLER", "ROLLS", "ROM", "ROMAN", "ROME", "RON", "RONALD", "ROOF", "ROOM", "ROOMS", "ROOT", "ROOTS", "ROPE", "ROSA", "ROSE", "ROSES", "ROSS", "ROSTER", "ROTARY", "ROUGE", "ROUGH", "ROUND", "ROUNDS", "ROUTE", "ROUTER", "ROUTES", "ROVER", "ROW", "ROWS", "ROY", "ROYAL", "RPG", "RPM", "RRP", "RSS", "RUBBER", "RUBY", "RUG", "RUGBY", "RUGS", "RULE", "RULED", "RULES", "RULING", "RUN", "RUNNER", "RUNS", "RURAL", "RUSH", "RUSSIA", "RUTH", "RWANDA", "RYAN", "SACRED", "SAD", "SADDAM", "SAFARI", "SAFE", "SAFELY", "SAFER", "SAFETY", "SAGE", "SAGEM", "SAID", "SAIL", "SAINT", "SAINTS", "SAKE", "SALAD", "SALARY", "SALE", "SALEM", "SALES", "SALLY", "SALMON", "SALON", "SALT", "SAM", "SAMBA", "SAME", "SAMOA", "SAMPLE", "SAMUEL", "SAN", "SAND", "SANDRA", "SANDY", "SANS", "SANTA", "SANYO", "SAO", "SAP", "SARA", "SARAH", "SAS", "SAT", "SATIN", "SATURN", "SAUCE", "SAUDI", "SAVAGE", "SAVE", "SAVED", "SAVER", "SAVES", "SAVING", "SAW", "SAY", "SAYING", "SAYS", "SBJCT", "SCALE", "SCALES", "SCAN", "SCARED", "SCARY", "SCENE", "SCENES", "SCENIC", "SCHEMA", "SCHEME", "SCHOOL", "SCI", "SCOOP", "SCOPE", "SCORE", "SCORED", "SCORES", "SCOTIA", "SCOTT", "SCOUT", "SCREEN", "SCREW", "SCRIPT", "SCROLL", "SCSI", "SCUBA", "SEA", "SEAL", "SEALED", "SEAN", "SEARCH", "SEAS", "SEASON", "SEAT", "SEATS", "SEC", "SECOND", "SECRET", "SECTOR", "SECURE", "SEE", "SEED", "SEEDS", "SEEING", "SEEK", "SEEKER", "SEEKS", "SEEM", "SEEMED", "SEEMS", "SEEN", "SEES", "SEGA", "SELECT", "SELF", "SELL", "SELLER", "SELLS", "SEMI", "SEN", "SENATE", "SEND", "SENDER", "SENDS", "SENIOR", "SENSE", "SENSOR", "SENT", "SEO", "SEP", "SEPT", "SEQ", "SER", "SERBIA", "SERIAL", "SERIES", "SERUM", "SERVE", "SERVED", "SERVER", "SERVES", "SET", "SETS", "SETTLE", "SETUP", "SEVEN", "SEVERE", "SEWING", "SEXUAL", "SHADE", "SHADES", "SHADOW", "SHAFT", "SHAKE", "SHALL", "SHAME", "SHAPE", "SHAPED", "SHAPES", "SHARE", "SHARED", "SHARES", "SHARK", "SHARON", "SHARP", "SHAVED", "SHAW", "SHE", "SHED", "SHEEP", "SHEER", "SHEET", "SHEETS", "SHELF", "SHELL", "SHIELD", "SHIFT", "SHINE", "SHIP", "SHIPS", "SHIRT", "SHIRTS", "SHOCK", "SHOE", "SHOES", "SHOOT", "SHOP", "SHOPS", "SHORE", "SHORT", "SHORTS", "SHOT", "SHOTS", "SHOULD", "SHOW", "SHOWED", "SHOWER", "SHOWN", "SHOWS", "SHUT", "SIC", "SICK", "SIDE", "SIDES", "SIE", "SIERRA", "SIG", "SIGHT", "SIGMA", "SIGN", "SIGNAL", "SIGNED", "SIGNS", "SIGNUP", "SILENT", "SILK", "SILLY", "SILVER", "SIM", "SIMON", "SIMPLE", "SIMPLY", "SIMS", "SIN", "SINCE", "SING", "SINGER", "SINGH", "SINGLE", "SINK", "SIP", "SIR", "SISTER", "SIT", "SITE", "SITES", "SIX", "SIXTH", "SIZE", "SIZED", "SIZES", "SKI", "SKIING", "SKILL", "SKILLS", "SKIN", "SKINS", "SKIP", "SKIRT", "SKIRTS", "SKU", "SKY", "SKYPE", "SLAVE", "SLEEP", "SLEEPS", "SLEEVE", "SLIDE", "SLIDES", "SLIGHT", "SLIM", "SLIP", "SLOPE", "SLOT", "SLOTS", "SLOVAK", "SLOW", "SLOWLY", "SMALL", "SMART", "SMELL", "SMILE", "SMITH", "SMOKE", "SMOOTH", "SMS", "SMTP", "SNAKE", "SNAP", "SNOW", "SOA", "SOAP", "SOC", "SOCCER", "SOCIAL", "SOCKET", "SOCKS", "SODIUM", "SOFA", "SOFT", "SOIL", "SOL", "SOLAR", "SOLD", "SOLE", "SOLELY", "SOLID", "SOLO", "SOLVE", "SOLVED", "SOMA", "SOME", "SON", "SONG", "SONGS", "SONIC", "SONS", "SONY", "SOON", "SORRY", "SORT", "SORTED", "SORTS", "SOUGHT", "SOUL", "SOULS", "SOUND", "SOUNDS", "SOUP", "SOURCE", "SOUTH", "SOVIET", "SOX", "SPA", "SPACE", "SPACES", "SPAIN", "SPAM", "SPAN", "SPANK", "SPARC", "SPARE", "SPAS", "SPEAK", "SPEAKS", "SPEARS", "SPEC", "SPECS", "SPEECH", "SPEED", "SPEEDS", "SPELL", "SPEND", "SPENT", "SPERM", "SPHERE", "SPICE", "SPIDER", "SPIES", "SPIN", "SPINE", "SPIRIT", "SPLIT", "SPOKE", "SPOKEN", "SPORT", "SPORTS", "SPOT", "SPOTS", "SPOUSE", "SPRAY", "SPREAD", "SPRING", "SPRINT", "SPY", "SQL", "SQUAD", "SQUARE", "SRC", "SRI", "SSL", "STABLE", "STACK", "STAFF", "STAGE", "STAGES", "STAKE", "STAMP", "STAMPS", "STAN", "STAND", "STANDS", "STAR", "STARS", "START", "STARTS", "STAT", "STATE", "STATED", "STATES", "STATIC", "STATS", "STATUS", "STAY", "STAYED", "STAYS", "STD", "STE", "STEADY", "STEAL", "STEAM", "STEEL", "STEM", "STEP", "STEPS", "STEREO", "STEVE", "STEVEN", "STICK", "STICKS", "STICKY", "STILL", "STOCK", "STOCKS", "STOLEN", "STONE", "STONES", "STOOD", "STOP", "STOPS", "STORE", "STORED", "STORES", "STORM", "STORY", "STR", "STRAIN", "STRAND", "STRAP", "STREAM", "STREET", "STRESS", "STRICT", "STRIKE", "STRING", "STRIP", "STRIPS", "STROKE", "STRONG", "STRUCK", "STRUCT", "STUART", "STUCK", "STUD", "STUDIO", "STUDY", "STUFF", "STUPID", "STYLE", "STYLES", "STYLUS", "SUB", "SUBARU", "SUBMIT", "SUBTLE", "SUCH", "SUDAN", "SUDDEN", "SUE", "SUFFER", "SUGAR", "SUIT", "SUITE", "SUITED", "SUITES", "SUITS", "SUM", "SUMMER", "SUMMIT", "SUN", "SUNDAY", "SUNNY", "SUNSET", "SUPER", "SUPERB", "SUPPLY", "SUR", "SURE", "SURELY", "SURF", "SURGE", "SURREY", "SURVEY", "SUSAN", "SUSE", "SUSSEX", "SUZUKI", "SWAP", "SWEDEN", "SWEET", "SWIFT", "SWIM", "SWING", "SWISS", "SWITCH", "SWORD", "SYDNEY", "SYMBOL", "SYNC", "SYNTAX", "SYRIA", "SYS", "SYSTEM", "TAB", "TABLE", "TABLES", "TABLET", "TABS", "TACKLE", "TAG", "TAGGED", "TAGS", "TAHOE", "TAIL", "TAIWAN", "TAKE", "TAKEN", "TAKES", "TAKING", "TALE", "TALENT", "TALES", "TALK", "TALKED", "TALKS", "TALL", "TAMIL", "TAMPA", "TAN", "TANK", "TANKS", "TAP", "TAPE", "TAPES", "TAR", "TARGET", "TARIFF", "TASK", "TASKS", "TASTE", "TATTOO", "TAUGHT", "TAX", "TAXES", "TAXI", "TAYLOR", "TBA", "TCP", "TEA", "TEACH", "TEAM", "TEAMS", "TEAR", "TEARS", "TECH", "TECHNO", "TED", "TEDDY", "TEE", "TEEN", "TEENS", "TEETH", "TEL", "TELL", "TELLS", "TEMP", "TEMPLE", "TEN", "TENANT", "TEND", "TENDER", "TENNIS", "TENT", "TERM", "TERMS", "TERROR", "TERRY", "TEST", "TESTED", "TESTS", "TEX", "TEXAS", "TEXT", "TEXTS", "TFT", "TGP", "THAI", "THAN", "THANK", "THANKS", "THAT", "THATS", "THE", "THEE", "THEFT", "THEHUN", "THEIR", "THEM", "THEME", "THEMES", "THEN", "THEORY", "THERE", "THESE", "THESIS", "THETA", "THEY", "THICK", "THIN", "THING", "THINGS", "THINK", "THINKS", "THIRD", "THIRTY", "THIS", "THOMAS", "THONG", "THONGS", "THOSE", "THOU", "THOUGH", "THREAD", "THREAT", "THREE", "THROAT", "THROW", "THROWN", "THROWS", "THRU", "THU", "THUMB", "THUMBS", "THUS", "THY", "TICKET", "TIDE", "TIE", "TIED", "TIER", "TIES", "TIGER", "TIGERS", "TIGHT", "TIL", "TILE", "TILES", "TILL", "TIM", "TIMBER", "TIME", "TIMELY", "TIMER", "TIMES", "TIMING", "TIN", "TINY", "TION", "TIONS", "TIP", "TIPS", "TIRE", "TIRED", "TIRES", "TISSUE", "TITANS", "TITLE", "TITLED", "TITLES", "TITTEN", "TMP", "TOBAGO", "TODAY", "TODD", "TOE", "TOILET", "TOKEN", "TOKYO", "TOLD", "TOLL", "TOM", "TOMATO", "TOMMY", "TON", "TONE", "TONER", "TONES", "TONGUE", "TONS", "TONY", "TOO", "TOOK", "TOOL", "TOOLS", "TOOTH", "TOP", "TOPIC", "TOPICS", "TOPS", "TOTAL", "TOTALS", "TOUCH", "TOUGH", "TOUR", "TOURS", "TOWARD", "TOWER", "TOWERS", "TOWN", "TOWNS", "TOXIC", "TOY", "TOYOTA", "TOYS", "TRACE", "TRACK", "TRACKS", "TRACT", "TRACY", "TRADE", "TRADER", "TRADES", "TRAIL", "TRAILS", "TRAIN", "TRAINS", "TRANCE", "TRANS", "TRAP", "TRASH", "TRAUMA", "TRAVEL", "TRAVIS", "TRAY", "TREAT", "TREATY", "TREE", "TREES", "TREK", "TREMBL", "TREND", "TRENDS", "TREO", "TRI", "TRIAL", "TRIALS", "TRIBAL", "TRIBE", "TRIBES", "TRICK", "TRICKS", "TRIED", "TRIES", "TRIM", "TRIO", "TRIP", "TRIPLE", "TRIPS", "TRIVIA", "TROOPS", "TROUT", "TROY", "TRUCK", "TRUCKS", "TRUE", "TRULY", "TRUNK", "TRUST", "TRUSTS", "TRUTH", "TRY", "TRYING", "TUB", "TUBE", "TUBES", "TUCSON", "TUE", "TULSA", "TUMOR", "TUNE", "TUNER", "TUNES", "TUNING", "TUNNEL", "TURBO", "TURKEY", "TURN", "TURNED", "TURNER", "TURNS", "TURTLE", "TVS", "TWELVE", "TWENTY", "TWICE", "TWIKI", "TWIN", "TWINS", "TWIST", "TWO", "TYLER", "TYPE", "TYPES", "TYPING", "UGANDA", "UGLY", "ULTRA", "ULTRAM", "UNA", "UNABLE", "UNCLE", "UND", "UNDER", "UNDO", "UNE", "UNI", "UNION", "UNIONS", "UNIQUE", "UNIT", "UNITED", "UNITS", "UNITY", "UNIV", "UNIX", "UNLESS", "UNLIKE", "UNLOCK", "UNTIL", "UNTO", "UNWRAP", "UPC", "UPDATE", "UPLOAD", "UPON", "UPPER", "UPS", "UPSET", "URBAN", "URGE", "URGENT", "URI", "URL", "URLS", "URW", "USA", "USAGE", "USB", "USC", "USD", "USDA", "USE", "USED", "USEFUL", "USER", "USERS", "USES", "USGS", "USING", "USPS", "USR", "USUAL", "UTAH", "UTC", "UTILS", "VACUUM", "VAL", "VALID", "VALIUM", "VALLEY", "VALUE", "VALUED", "VALUES", "VALVE", "VALVES", "VAN", "VAR", "VARIED", "VARIES", "VARY", "VAST", "VAT", "VAULT", "VCR", "VECTOR", "VEGAS", "VELVET", "VENDOR", "VENICE", "VENUE", "VENUES", "VER", "VERBAL", "VERDE", "VERIFY", "VERNON", "VERSE", "VERSUS", "VERTEX", "VERY", "VESSEL", "VHS", "VIA", "VIC", "VICE", "VICTIM", "VICTOR", "VID", "VIDEO", "VIDEOS", "VIDS", "VIENNA", "VIEW", "VIEWED", "VIEWER", "VIEWS", "VII", "VIII", "VIKING", "VILLA", "VILLAS", "VINYL", "VIOLIN", "VIP", "VIRAL", "VIRGIN", "VIRTUE", "VIRUS", "VISA", "VISION", "VISIT", "VISITS", "VISTA", "VISUAL", "VITAL", "VOCAL", "VOCALS", "VOICE", "VOICES", "VOID", "VOIP", "VOL", "VOLT", "VOLUME", "VOLVO", "VON", "VOTE", "VOTED", "VOTERS", "VOTES", "VOTING", "VOYUER", "VPN", "VSNET", "WAGE", "WAGES", "WAGNER", "WAGON", "WAIT", "WAIVER", "WAKE", "WAL", "WALES", "WALK", "WALKED", "WALKER", "WALKS", "WALL", "WALLET", "WALLS", "WALNUT", "WALT", "WALTER", "WAN", "WANNA", "WANT", "WANTED", "WANTS", "WAR", "WARD", "WARE", "WARM", "WARNED", "WARNER", "WARREN", "WARS", "WAS", "WASH", "WASHER", "WASTE", "WATCH", "WATER", "WATERS", "WATSON", "WATT", "WATTS", "WAV", "WAVE", "WAVES", "WAX", "WAY", "WAYNE", "WAYS", "WEAK", "WEALTH", "WEAPON", "WEAR", "WEB", "WEBCAM", "WEBLOG", "WED", "WEED", "WEEK", "WEEKLY", "WEEKS", "WEIGHT", "WEIRD", "WELL", "WELLS", "WELSH", "WENDY", "WENT", "WERE", "WESLEY", "WEST", "WET", "WHALE", "WHAT", "WHATS", "WHEAT", "WHEEL", "WHEELS", "WHEN", "WHERE", "WHICH", "WHILE", "WHILST", "WHITE", "WHO", "WHOLE", "WHOM", "WHOSE", "WHY", "WICKED", "WIDE", "WIDELY", "WIDER", "WIDTH", "WIFE", "WIFI", "WIKI", "WILD", "WILEY", "WILL", "WILLOW", "WILSON", "WIN", "WIND", "WINDOW", "WINDS", "WINE", "WINES", "WING", "WINGS", "WINNER", "WINS", "WINTER", "WIRE", "WIRED", "WIRES", "WIRING", "WISDOM", "WISE", "WISH", "WISHES", "WIT", "WITCH", "WITH", "WITHIN", "WIVES", "WIZARD", "WMA", "WOLF", "WOMAN", "WOMEN", "WOMENS", "WON", "WONDER", "WOOD", "WOODEN", "WOODS", "WOOL", "WORD", "WORDS", "WORK", "WORKED", "WORKER", "WORKS", "WORLD", "WORLDS", "WORM", "WORN", "WORRY", "WORSE", "WORST", "WORTH", "WORTHY", "WOULD", "WOUND", "WOW", "WRAP", "WRIGHT", "WRIST", "WRITE", "WRITER", "WRITES", "WRONG", "WROTE", "WTO", "WWW", "XANAX", "XBOX", "XEROX", "XHTML", "XML", "YACHT", "YAHOO", "YALE", "YAMAHA", "YANG", "YARD", "YARDS", "YARN", "YEA", "YEAH", "YEAR", "YEARLY", "YEARS", "YEAST", "YELLOW", "YEMEN", "YEN", "YES", "YET", "YIELD", "YIELDS", "YOGA", "YORK", "YOU", "YOUNG", "YOUR", "YOURS", "YOUTH", "YRS", "YUKON", "ZAMBIA", "ZDNET", "ZEN", "ZERO", "ZINC", "ZIP", "ZOLOFT", "ZONE", "ZONES", "ZONING", "ZOO", "ZOOM", "ZOPE", "ZSHOPS", "ZUM", "ZUS"];

const HTML_PAGE = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>SixRoll</title>
<style>
  :root { color-scheme: dark; }
  * { box-sizing: border-box; }
  body {
    font-family: system-ui, -apple-system, sans-serif;
    background: #0f172a;
    color: #e2e8f0;
    max-width: 560px;
    margin: 30px auto;
    padding: 0 20px 60px;
  }
  h1 { font-size: 1.6rem; margin-bottom: 2px; }
  p.sub { color: #94a3b8; margin-top: 0; font-size: 0.9rem; }

  .name-row { display: flex; gap: 8px; margin: 16px 0; align-items: center; }
  .name-row label { font-size: 0.8rem; color: #94a3b8; white-space: nowrap; }
  .name-row input {
    flex: 1; background: #1e293b; border: 1px solid #334155; border-radius: 6px;
    padding: 8px 10px; color: #e2e8f0; font-size: 0.9rem;
  }

  .tiles { display: flex; gap: 8px; justify-content: center; margin: 24px 0 16px; perspective: 600px; }
  .tile {
    width: 52px; height: 60px; background: #1e293b; border: 2px solid #334155;
    border-radius: 8px; display: flex; align-items: center; justify-content: center;
    font-size: 1.6rem; font-weight: 700; text-transform: uppercase;
    transition: transform 0.15s ease, border-color 0.3s ease, background 0.3s ease;
  }
  .tile.settled { border-color: #6366f1; background: #24243f; }

  .roll-row { display: flex; flex-direction: column; align-items: center; gap: 6px; margin: 20px 0; }
  button.roll {
    background: #6366f1; border: none; border-radius: 8px; padding: 12px 28px;
    color: white; font-weight: 700; font-size: 1rem; cursor: pointer;
  }
  button.roll:disabled { background: #334155; color: #64748b; cursor: not-allowed; }
  button.roll:not(:disabled):hover { background: #4f46e5; }
  #cooldownText { font-size: 0.8rem; color: #94a3b8; min-height: 1.2em; }
  #unlimitedBadge {
    display: none; font-size: 0.7rem; color: #facc15; border: 1px solid #facc15;
    border-radius: 999px; padding: 2px 10px; margin-top: 4px;
  }

  .result {
    background: #131c2e; border: 1px solid #334155; border-radius: 10px;
    padding: 16px; margin: 16px 0; display: none;
  }
  .result.show { display: block; }
  .result h3 { margin: 0 0 4px; font-size: 1.1rem; }
  .rarity-tag {
    display: inline-block; font-size: 0.75rem; font-weight: 700; padding: 3px 10px;
    border-radius: 999px; margin-bottom: 10px; text-transform: uppercase; letter-spacing: 0.03em;
  }
  .badge-list { list-style: none; padding: 0; margin: 0; display: flex; flex-direction: column; gap: 6px; }
  .badge-item {
    display: flex; justify-content: space-between; gap: 10px; font-size: 0.88rem;
    background: #1e293b; border-radius: 6px; padding: 8px 10px;
  }
  .badge-name { font-weight: 600; }
  .badge-desc { color: #94a3b8; font-size: 0.78rem; display: block; }
  .badge-ep { color: #4ade80; font-weight: 700; white-space: nowrap; }
  .supporting { margin-top: 10px; font-size: 0.78rem; color: #64748b; }
  .total-ep { margin-top: 12px; font-size: 1rem; text-align: right; font-weight: 700; }

  table { width: 100%; border-collapse: collapse; margin-top: 10px; }
  th, td { text-align: left; padding: 8px; border-bottom: 1px solid #1e293b; font-size: 0.9rem; }
  th { color: #94a3b8; font-size: 0.75rem; text-transform: uppercase; }
  tr:first-child td { color: #facc15; font-weight: 700; }
  h2 { font-size: 1.1rem; margin-top: 36px; margin-bottom: 8px; }
  #toast {
    position: fixed; bottom: 20px; left: 50%; transform: translateX(-50%);
    background: #1e293b; border: 1px solid #6366f1; padding: 8px 16px; border-radius: 8px;
    font-size: 0.85rem; opacity: 0; transition: opacity 0.3s ease; pointer-events: none;
  }
  #toast.show { opacity: 1; }
</style>
</head>
<body>
  <h1>🎲 SixRoll</h1>
  <p class="sub">Roll six random letters. Score badges for patterns and real words hidden in your pull.</p>

  <div class="name-row">
    <label for="nameInput">Name</label>
    <input id="nameInput" maxlength="20" placeholder="Enter a name for the leaderboard">
  </div>

  <div class="tiles" id="tiles"></div>

  <div class="roll-row">
    <button class="roll" id="rollBtn">Roll</button>
    <div id="cooldownText"></div>
    <div id="unlimitedBadge">TEST MODE: unlimited rolls</div>
  </div>

  <div class="result" id="result">
    <h3 id="resultTitle"></h3>
    <span class="rarity-tag" id="rarityTag"></span>
    <ul class="badge-list" id="badgeList"></ul>
    <div class="supporting" id="supporting"></div>
    <div class="total-ep" id="totalEp"></div>
  </div>

  <h2>Leaderboard</h2>
  <table>
    <thead><tr><th>#</th><th>Name</th><th>Total EP</th><th>Rolls</th><th>Best Roll</th></tr></thead>
    <tbody id="lbBody"></tbody>
  </table>

  <div id="toast"></div>

<script>
var WORDS = new Set(["AAA", "AARON", "ABC", "ABLE", "ABOUT", "ABOVE", "ABROAD", "ABS", "ABSENT", "ABU", "ABUSE", "ACC", "ACCENT", "ACCEPT", "ACCESS", "ACE", "ACER", "ACID", "ACIDS", "ACM", "ACNE", "ACRE", "ACRES", "ACROSS", "ACT", "ACTING", "ACTION", "ACTIVE", "ACTOR", "ACTORS", "ACTS", "ACTUAL", "ACUTE", "ADA", "ADAM", "ADAMS", "ADD", "ADDED", "ADDING", "ADDS", "ADIDAS", "ADIPEX", "ADJUST", "ADMIN", "ADMIT", "ADOBE", "ADOPT", "ADRIAN", "ADS", "ADSL", "ADULT", "ADULTS", "ADVERT", "ADVICE", "ADVISE", "ADWARE", "AERIAL", "AFFAIR", "AFFECT", "AFFORD", "AFRAID", "AFRICA", "AFTER", "AGAIN", "AGE", "AGED", "AGENCY", "AGENDA", "AGENT", "AGENTS", "AGES", "AGING", "AGO", "AGREE", "AGREED", "AGREES", "AHEAD", "AID", "AIDS", "AIM", "AIMED", "AIMS", "AIR", "AKA", "ALA", "ALAN", "ALARM", "ALASKA", "ALBANY", "ALBERT", "ALBUM", "ALBUMS", "ALERT", "ALERTS", "ALEX", "ALFRED", "ALI", "ALIAS", "ALICE", "ALIEN", "ALIGN", "ALIKE", "ALIVE", "ALL", "ALLAH", "ALLAN", "ALLEN", "ALLIED", "ALLOW", "ALLOWS", "ALLOY", "ALMOST", "ALONE", "ALONG", "ALOT", "ALPHA", "ALPINE", "ALSO", "ALT", "ALTER", "ALTO", "ALUMNI", "ALWAYS", "AMANDA", "AMAZON", "AMBER", "AMBIEN", "AMD", "AMEND", "AMINO", "AMONG", "AMOUNT", "AMP", "AMY", "ANA", "ANALOG", "ANCHOR", "AND", "ANDALE", "ANDREA", "ANDREW", "ANDY", "ANGEL", "ANGELA", "ANGELS", "ANGER", "ANGLE", "ANGOLA", "ANGRY", "ANIMAL", "ANIME", "ANN", "ANNA", "ANNE", "ANNEX", "ANNIE", "ANNUAL", "ANSWER", "ANT", "ANTI", "ANY", "ANYONE", "ANYWAY", "AOL", "APACHE", "APART", "API", "APNIC", "APOLLO", "APP", "APPEAL", "APPEAR", "APPLE", "APPLY", "APPROX", "APPS", "APR", "APRIL", "APT", "AQUA", "ARAB", "ARABIA", "ARABIC", "ARBOR", "ARC", "ARCADE", "ARCH", "ARCTIC", "ARE", "AREA", "AREAS", "ARENA", "ARG", "ARGUE", "ARGUED", "ARISE", "ARM", "ARMED", "ARMOR", "ARMS", "ARMY", "ARNOLD", "AROUND", "ARRAY", "ARREST", "ARRIVE", "ARROW", "ART", "ARTHUR", "ARTIST", "ARTS", "ARUBA", "ASCII", "ASH", "ASHLEY", "ASIA", "ASIAN", "ASIDE", "ASIN", "ASK", "ASKED", "ASKING", "ASKS", "ASN", "ASP", "ASPECT", "ASSESS", "ASSET", "ASSETS", "ASSIGN", "ASSIST", "ASSUME", "ASSURE", "ASTHMA", "ASUS", "ASYLUM", "ATA", "ATE", "ATHENS", "ATI", "ATLAS", "ATM", "ATOM", "ATOMIC", "ATTACH", "ATTACK", "ATTEND", "AUBURN", "AUD", "AUDI", "AUDIO", "AUDIT", "AUG", "AUGUST", "AURORA", "AUS", "AUSTIN", "AUTHOR", "AUTO", "AUTOS", "AUTUMN", "AVATAR", "AVE", "AVENUE", "AVG", "AVI", "AVOID", "AVON", "AWARD", "AWARDS", "AWARE", "AWAY", "AWFUL", "AXIS", "AYE", "BABE", "BABES", "BABIES", "BABY", "BACK", "BACKED", "BACKUP", "BACON", "BAD", "BADGE", "BADLY", "BAG", "BAGS", "BAILEY", "BAKER", "BAKING", "BALD", "BALI", "BALL", "BALLET", "BALLOT", "BAN", "BANANA", "BAND", "BANDS", "BANG", "BANK", "BANKS", "BANNED", "BANNER", "BAR", "BARBIE", "BARE", "BARELY", "BARN", "BARNES", "BARREL", "BARRY", "BARS", "BASE", "BASED", "BASES", "BASIC", "BASICS", "BASIN", "BASIS", "BASKET", "BASS", "BAT", "BATCH", "BATH", "BATHS", "BATMAN", "BATTLE", "BAY", "BBC", "BBS", "BEACH", "BEADS", "BEAM", "BEAN", "BEANS", "BEAR", "BEARS", "BEAST", "BEAT", "BEATS", "BEAUTY", "BEAVER", "BECAME", "BECOME", "BED", "BEDS", "BEE", "BEEF", "BEEN", "BEER", "BEFORE", "BEGAN", "BEGIN", "BEGINS", "BEGUN", "BEHALF", "BEHIND", "BEING", "BEINGS", "BELIEF", "BELIZE", "BELKIN", "BELL", "BELLE", "BELLY", "BELONG", "BELOW", "BELT", "BELTS", "BEN", "BENCH", "BEND", "BENT", "BENZ", "BERLIN", "BERRY", "BESIDE", "BEST", "BET", "BETA", "BETH", "BETTER", "BETTY", "BEYOND", "BHUTAN", "BIAS", "BIBLE", "BID", "BIDDER", "BIDS", "BIG", "BIGGER", "BIKE", "BIKES", "BIKINI", "BILL", "BILLS", "BILLY", "BIN", "BINARY", "BIND", "BINGO", "BIO", "BIOL", "BIOS", "BIRD", "BIRDS", "BIRTH", "BISHOP", "BIT", "BITE", "BITS", "BIZ", "BLACK", "BLACKS", "BLADE", "BLADES", "BLAH", "BLAIR", "BLAKE", "BLAME", "BLANK", "BLAST", "BLEND", "BLESS", "BLIND", "BLINK", "BLOCK", "BLOCKS", "BLOG", "BLOGS", "BLOND", "BLONDE", "BLOOD", "BLOOM", "BLOW", "BLUE", "BLUES", "BLVD", "BMW", "BOARD", "BOARDS", "BOAT", "BOATS", "BOB", "BOBBY", "BOC", "BODIES", "BODY", "BOLD", "BOLT", "BOMB", "BON", "BOND", "BONDS", "BONE", "BONES", "BONUS", "BOOK", "BOOKS", "BOOL", "BOOM", "BOOST", "BOOT", "BOOTH", "BOOTS", "BOOTY", "BORDER", "BORED", "BORING", "BORN", "BOSNIA", "BOSS", "BOSTON", "BOTH", "BOTHER", "BOTTLE", "BOTTOM", "BOUGHT", "BOUND", "BOW", "BOWL", "BOX", "BOXED", "BOXES", "BOXING", "BOY", "BOYS", "BRA", "BRAD", "BRAIN", "BRAKE", "BRAKES", "BRANCH", "BRAND", "BRANDS", "BRAS", "BRASS", "BRAVE", "BRAZIL", "BREACH", "BREAD", "BREAK", "BREAKS", "BREAST", "BREATH", "BREED", "BREEDS", "BRIAN", "BRICK", "BRIDAL", "BRIDE", "BRIDGE", "BRIEF", "BRIEFS", "BRIGHT", "BRING", "BRINGS", "BROAD", "BROKE", "BROKEN", "BROKER", "BRONZE", "BROOK", "BROOKS", "BROWN", "BROWSE", "BRUCE", "BRUNEI", "BRUSH", "BRUTAL", "BRYAN", "BRYANT", "BUBBLE", "BUCK", "BUCKS", "BUDDY", "BUDGET", "BUF", "BUFFER", "BUFING", "BUG", "BUGS", "BUILD", "BUILDS", "BUILT", "BULK", "BULL", "BULLET", "BUMPER", "BUNCH", "BUNDLE", "BUNNY", "BURDEN", "BUREAU", "BURIED", "BURKE", "BURN", "BURNER", "BURNS", "BURST", "BURTON", "BUS", "BUSES", "BUSH", "BUSY", "BUT", "BUTLER", "BUTTER", "BUTTON", "BUTTS", "BUY", "BUYER", "BUYERS", "BUYING", "BUYS", "BUZZ", "BYE", "BYTE", "BYTES", "CAB", "CABIN", "CABLE", "CABLES", "CACHE", "CACHED", "CAD", "CAFE", "CAGE", "CAKE", "CAKES", "CAL", "CALL", "CALLED", "CALLS", "CALM", "CALVIN", "CAM", "CAME", "CAMEL", "CAMERA", "CAMP", "CAMPS", "CAMPUS", "CAMS", "CAN", "CANADA", "CANAL", "CANCEL", "CANCER", "CANDLE", "CANDY", "CANNON", "CANON", "CANT", "CANVAS", "CANYON", "CAP", "CAPE", "CAPS", "CAR", "CARB", "CARBON", "CARD", "CARDS", "CARE", "CAREER", "CAREY", "CARGO", "CARING", "CARL", "CARLO", "CARLOS", "CARMEN", "CAROL", "CARPET", "CARRY", "CARS", "CART", "CARTER", "CAS", "CASA", "CASE", "CASES", "CASEY", "CASH", "CASINO", "CASIO", "CAST", "CASTLE", "CASUAL", "CAT", "CATCH", "CATS", "CATTLE", "CAUGHT", "CAUSE", "CAUSED", "CAUSES", "CAVE", "CAYMAN", "CBS", "CCD", "CDNA", "CDS", "CDT", "CEDAR", "CELEBS", "CELL", "CELLS", "CELTIC", "CEMENT", "CENSUS", "CENT", "CENTER", "CENTRE", "CENTS", "CEO", "CET", "CFR", "CGI", "CHAD", "CHAIN", "CHAINS", "CHAIR", "CHAIRS", "CHAN", "CHANCE", "CHANGE", "CHAOS", "CHAPEL", "CHAR", "CHARGE", "CHARM", "CHARMS", "CHART", "CHARTS", "CHASE", "CHAT", "CHEAP", "CHEAT", "CHEATS", "CHECK", "CHECKS", "CHEERS", "CHEESE", "CHEF", "CHEM", "CHEN", "CHEQUE", "CHERRY", "CHESS", "CHEST", "CHEVY", "CHI", "CHICK", "CHICKS", "CHIEF", "CHILD", "CHILE", "CHINA", "CHIP", "CHIPS", "CHO", "CHOICE", "CHOIR", "CHOOSE", "CHORUS", "CHOSE", "CHOSEN", "CHRIS", "CHRIST", "CHROME", "CHUBBY", "CHUCK", "CHURCH", "CIA", "CIALIS", "CIAO", "CINDY", "CINEMA", "CIO", "CIR", "CIRCLE", "CIRCUS", "CISCO", "CITE", "CITED", "CITIES", "CITY", "CIVIC", "CIVIL", "CLAIM", "CLAIMS", "CLAIRE", "CLAN", "CLARA", "CLARK", "CLARKE", "CLASS", "CLAUSE", "CLAY", "CLEAN", "CLEAR", "CLERK", "CLICK", "CLICKS", "CLIENT", "CLIFF", "CLIMB", "CLINIC", "CLIP", "CLIPS", "CLOCK", "CLOCKS", "CLONE", "CLOSE", "CLOSED", "CLOSER", "CLOSES", "CLOTH", "CLOUD", "CLOUDS", "CLOUDY", "CLUB", "CLUBS", "CMS", "CNET", "CNN", "COACH", "COAL", "COAST", "COAT", "COATED", "COD", "CODE", "CODES", "CODING", "COFFEE", "COHEN", "COIN", "COINS", "COL", "COLD", "COLE", "COLIN", "COLLAR", "COLON", "COLONY", "COLOR", "COLORS", "COLOUR", "COLUMN", "COM", "COMBAT", "COMBO", "COME", "COMEDY", "COMES", "COMIC", "COMICS", "COMING", "COMM", "COMMIT", "COMMON", "COMP", "COMPAQ", "COMPLY", "CON", "CONDO", "CONDOS", "CONF", "CONFIG", "CONGO", "CONS", "CONST", "COOK", "COOKED", "COOKIE", "COOL", "COOLER", "COOPER", "COP", "COPE", "COPIED", "COPIES", "COPPER", "COPY", "CORAL", "CORD", "CORE", "CORK", "CORN", "CORNER", "CORP", "CORPS", "CORPUS", "COS", "COST", "COSTA", "COSTS", "COTTON", "COULD", "COUNT", "COUNTS", "COUNTY", "COUPLE", "COUPON", "COURSE", "COURT", "COURTS", "COVE", "COVER", "COVERS", "COW", "COWBOY", "CPU", "CRACK", "CRADLE", "CRAFT", "CRAFTS", "CRAIG", "CRAPS", "CRASH", "CRAZY", "CREAM", "CREATE", "CREDIT", "CREEK", "CREST", "CREW", "CRIME", "CRIMES", "CRISIS", "CRM", "CROP", "CROPS", "CROSS", "CROWD", "CROWN", "CRUDE", "CRUISE", "CRUZ", "CRY", "CSS", "CST", "CTRL", "CUBA", "CUBE", "CUBIC", "CULT", "CUP", "CUPS", "CURE", "CURSOR", "CURTIS", "CURVE", "CURVES", "CUSTOM", "CUT", "CUTE", "CUTS", "CVS", "CYBER", "CYCLE", "CYCLES", "CYPRUS", "CZECH", "DAD", "DADDY", "DAILY", "DAIRY", "DAISY", "DAKOTA", "DALE", "DALLAS", "DAM", "DAMAGE", "DAME", "DAN", "DANA", "DANCE", "DANGER", "DANIEL", "DANISH", "DANNY", "DANS", "DARE", "DARK", "DARWIN", "DAS", "DASH", "DAT", "DATA", "DATE", "DATED", "DATES", "DATING", "DAVE", "DAVID", "DAVIS", "DAWN", "DAY", "DAYS", "DAYTON", "DDR", "DEAD", "DEADLY", "DEAF", "DEAL", "DEALER", "DEALS", "DEALT", "DEAN", "DEAR", "DEATH", "DEATHS", "DEBATE", "DEBIAN", "DEBT", "DEBUG", "DEBUT", "DEC", "DECADE", "DECENT", "DECIDE", "DECK", "DECOR", "DEE", "DEEMED", "DEEP", "DEEPER", "DEEPLY", "DEER", "DEF", "DEFEAT", "DEFEND", "DEFINE", "DEGREE", "DEL", "DELAY", "DELAYS", "DELETE", "DELHI", "DELL", "DELTA", "DELUXE", "DEM", "DEMAND", "DEMO", "DEN", "DENIAL", "DENIED", "DENNIS", "DENSE", "DENTAL", "DENVER", "DENY", "DEPEND", "DEPOT", "DEPT", "DEPTH", "DEPUTY", "DER", "DERBY", "DEREK", "DES", "DESERT", "DESIGN", "DESIRE", "DESK", "DETAIL", "DETECT", "DEV", "DEVEL", "DEVICE", "DEVIL", "DEVON", "DIAL", "DIALOG", "DIANA", "DIANE", "DIARY", "DICE", "DICKE", "DID", "DIE", "DIED", "DIEGO", "DIES", "DIESEL", "DIET", "DIFF", "DIFFER", "DIFFS", "DIG", "DIGEST", "DIGIT", "DIM", "DINING", "DINNER", "DIP", "DIR", "DIRECT", "DIRT", "DIRTY", "DIS", "DISC", "DISCO", "DISCS", "DISH", "DISHES", "DISK", "DISKS", "DISNEY", "DIST", "DIV", "DIVE", "DIVIDE", "DIVINE", "DIVING", "DIVX", "DIY", "DNA", "DNS", "DOC", "DOCK", "DOCS", "DOCTOR", "DOD", "DODGE", "DOE", "DOES", "DOG", "DOGS", "DOING", "DOLL", "DOLLAR", "DOLLS", "DOM", "DOMAIN", "DOME", "DON", "DONALD", "DONATE", "DONE", "DONNA", "DONOR", "DONORS", "DONT", "DOOM", "DOOR", "DOORS", "DOS", "DOSAGE", "DOSE", "DOT", "DOUBLE", "DOUBT", "DOUG", "DOVER", "DOW", "DOWN", "DOZEN", "DOZENS", "DPI", "DRAFT", "DRAG", "DRAGON", "DRAIN", "DRAMA", "DRAW", "DRAWN", "DRAWS", "DREAM", "DREAMS", "DRESS", "DREW", "DRIED", "DRILL", "DRINK", "DRINKS", "DRIVE", "DRIVEN", "DRIVER", "DRIVES", "DROP", "DROPS", "DROVE", "DRUG", "DRUGS", "DRUM", "DRUMS", "DRUNK", "DRY", "DRYER", "DSC", "DSL", "DTS", "DUAL", "DUBAI", "DUBLIN", "DUCK", "DUDE", "DUE", "DUI", "DUKE", "DUMB", "DUMP", "DUNCAN", "DUO", "DURHAM", "DURING", "DUST", "DUTCH", "DUTIES", "DUTY", "DVD", "DVDS", "DYING", "DYLAN", "EACH", "EAGLE", "EAGLES", "EAR", "EARL", "EARLY", "EARN", "EARNED", "EARS", "EARTH", "EASE", "EASIER", "EASILY", "EAST", "EASTER", "EASY", "EAT", "EATING", "EAU", "EBAY", "EBONY", "EBOOK", "EBOOKS", "ECHO", "ECO", "EDDIE", "EDEN", "EDGAR", "EDGE", "EDGES", "EDIT", "EDITED", "EDITOR", "EDS", "EDT", "EDWARD", "EFFECT", "EFFORT", "EGG", "EGGS", "EGYPT", "EIGHT", "EITHER", "ELDER", "ELECT", "ELEVEN", "ELITE", "ELLEN", "ELLIS", "ELSE", "ELVIS", "EMACS", "EMAIL", "EMAILS", "EMILY", "EMINEM", "EMMA", "EMPIRE", "EMPLOY", "EMPTY", "ENABLE", "ENB", "END", "ENDED", "ENDIF", "ENDING", "ENDS", "ENEMY", "ENERGY", "ENG", "ENGAGE", "ENGINE", "ENJOY", "ENOUGH", "ENSURE", "ENT", "ENTER", "ENTERS", "ENTIRE", "ENTITY", "ENTRY", "ENZYME", "EOS", "EPA", "EPIC", "EPSON", "EQUAL", "EQUITY", "ERA", "ERIC", "ERIK", "ERP", "ERROR", "ERRORS", "ESCAPE", "ESPN", "ESSAY", "ESSAYS", "ESSEX", "EST", "ESTATE", "ETC", "ETHICS", "ETHNIC", "EUGENE", "EUR", "EURO", "EUROPE", "EUROS", "EVA", "EVAL", "EVANS", "EVE", "EVEN", "EVENT", "EVENTS", "EVER", "EVERY", "EVIL", "EXACT", "EXAM", "EXAMS", "EXCEED", "EXCEL", "EXCEPT", "EXCESS", "EXCUSE", "EXEC", "EXEMPT", "EXIST", "EXISTS", "EXIT", "EXOTIC", "EXP", "EXPAND", "EXPECT", "EXPERT", "EXPO", "EXPORT", "EXT", "EXTEND", "EXTENT", "EXTRA", "EXTRAS", "EYE", "EYED", "EYES", "FABRIC", "FACE", "FACED", "FACES", "FACIAL", "FACING", "FACT", "FACTOR", "FACTS", "FAIL", "FAILED", "FAILS", "FAIR", "FAIRLY", "FAIRY", "FAITH", "FAKE", "FALL", "FALLEN", "FALLS", "FALSE", "FAME", "FAMILY", "FAMOUS", "FAN", "FANCY", "FANS", "FAQ", "FAQS", "FAR", "FARE", "FARES", "FARM", "FARMER", "FARMS", "FAST", "FASTER", "FAT", "FATAL", "FATE", "FATHER", "FATTY", "FAULT", "FAVOR", "FAVORS", "FAVOUR", "FAX", "FBI", "FCC", "FDA", "FEAR", "FEARS", "FEAT", "FEB", "FED", "FEE", "FEED", "FEEDS", "FEEL", "FEELS", "FEES", "FEET", "FELL", "FELLOW", "FELT", "FEMALE", "FENCE", "FEOF", "FERRY", "FETISH", "FEVER", "FEW", "FEWER", "FIBER", "FIBRE", "FIELD", "FIELDS", "FIFTH", "FIFTY", "FIG", "FIGHT", "FIGURE", "FIJI", "FILE", "FILED", "FILES", "FILING", "FILL", "FILLED", "FILM", "FILME", "FILMS", "FILTER", "FIN", "FINAL", "FINALS", "FIND", "FINDER", "FINDS", "FINE", "FINEST", "FINGER", "FINISH", "FINITE", "FIRE", "FIRED", "FIRES", "FIRM", "FIRMS", "FIRST", "FISCAL", "FISH", "FISHER", "FIST", "FIT", "FITS", "FITTED", "FIVE", "FIX", "FIXED", "FIXES", "FLAG", "FLAGS", "FLAME", "FLASH", "FLAT", "FLAVOR", "FLEECE", "FLEET", "FLESH", "FLEX", "FLICKR", "FLIGHT", "FLIP", "FLOAT", "FLOOD", "FLOOR", "FLOORS", "FLOPPY", "FLORAL", "FLOUR", "FLOW", "FLOWER", "FLOWS", "FLOYD", "FLU", "FLUID", "FLUSH", "FLUX", "FLY", "FLYER", "FLYING", "FOAM", "FOCAL", "FOCUS", "FOG", "FOLD", "FOLDER", "FOLK", "FOLKS", "FOLLOW", "FONT", "FONTS", "FOO", "FOOD", "FOODS", "FOOL", "FOOT", "FOR", "FORBES", "FORCE", "FORCED", "FORCES", "FORD", "FOREST", "FORGE", "FORGET", "FORGOT", "FORK", "FORM", "FORMAL", "FORMAT", "FORMED", "FORMER", "FORMS", "FORT", "FORTH", "FORTY", "FORUM", "FORUMS", "FOSSIL", "FOSTER", "FOTO", "FOTOS", "FOUGHT", "FOUL", "FOUND", "FOUR", "FOURTH", "FOX", "FRAME", "FRAMED", "FRAMES", "FRANCE", "FRANK", "FRASER", "FRAUD", "FRED", "FREE", "FREELY", "FREEZE", "FRENCH", "FRESH", "FRI", "FRIDAY", "FRIDGE", "FRIEND", "FROG", "FROM", "FRONT", "FROST", "FROZEN", "FRUIT", "FRUITS", "FTP", "FUEL", "FUJI", "FULL", "FULLY", "FUN", "FUND", "FUNDED", "FUNDS", "FUNK", "FUNKY", "FUNNY", "FUR", "FUSION", "FUTURE", "FUZZY", "FWD", "GAGE", "GAIN", "GAINED", "GAINS", "GALAXY", "GALE", "GAME", "GAMES", "GAMING", "GAMMA", "GANG", "GAP", "GAPS", "GARAGE", "GARCIA", "GARDEN", "GARLIC", "GARMIN", "GARY", "GAS", "GATE", "GATES", "GATHER", "GAUGE", "GAVE", "GAY", "GAYS", "GBA", "GBP", "GCC", "GDP", "GEAR", "GEEK", "GEL", "GEM", "GEN", "GENDER", "GENE", "GENES", "GENEVA", "GENIUS", "GENOME", "GENRE", "GENRES", "GENTLE", "GENTLY", "GEO", "GEORGE", "GERALD", "GERMAN", "GET", "GETS", "GHANA", "GHOST", "GHZ", "GIANT", "GIANTS", "GIBSON", "GIF", "GIFT", "GIFTS", "GIG", "GIRL", "GIRLS", "GIS", "GIVE", "GIVEN", "GIVES", "GIVING", "GLAD", "GLANCE", "GLASS", "GLEN", "GLENN", "GLOBAL", "GLOBE", "GLORY", "GLOVES", "GLOW", "GMBH", "GMC", "GMT", "GNOME", "GNU", "GOAL", "GOALS", "GOAT", "GODS", "GOES", "GOING", "GOLD", "GOLDEN", "GOLF", "GONE", "GONNA", "GOOD", "GOODS", "GOOGLE", "GORDON", "GORE", "GOSPEL", "GOSSIP", "GOT", "GOTHIC", "GOTO", "GOTTA", "GOTTEN", "GPL", "GPS", "GRAB", "GRACE", "GRAD", "GRADE", "GRADES", "GRAHAM", "GRAIN", "GRAMS", "GRAND", "GRANDE", "GRANNY", "GRANT", "GRANTS", "GRAPH", "GRAPHS", "GRAS", "GRASS", "GRATIS", "GRAVE", "GRAY", "GREAT", "GREECE", "GREEK", "GREEN", "GREENE", "GREG", "GREW", "GREY", "GRID", "GRILL", "GRIP", "GROOVE", "GROSS", "GROUND", "GROUP", "GROUPS", "GROVE", "GROW", "GROWN", "GROWS", "GROWTH", "GSM", "GST", "GTK", "GUAM", "GUARD", "GUARDS", "GUESS", "GUEST", "GUESTS", "GUI", "GUIDE", "GUIDED", "GUIDES", "GUILD", "GUILTY", "GUINEA", "GUITAR", "GULF", "GUN", "GUNS", "GURU", "GUY", "GUYANA", "GUYS", "GYM", "GZIP", "HABITS", "HACK", "HACKER", "HAD", "HAIR", "HAIRY", "HAITI", "HALF", "HALL", "HALO", "HAM", "HAMMER", "HAND", "HANDED", "HANDLE", "HANDS", "HANDY", "HANG", "HANS", "HANSEN", "HAPPEN", "HAPPY", "HARBOR", "HARD", "HARDER", "HARDLY", "HARLEY", "HARM", "HAROLD", "HARPER", "HARRIS", "HARRY", "HART", "HARVEY", "HAS", "HASH", "HAT", "HATE", "HATS", "HAVE", "HAVEN", "HAVING", "HAWAII", "HAWK", "HAY", "HAYES", "HAZARD", "HDTV", "HEAD", "HEADED", "HEADER", "HEADS", "HEALTH", "HEAR", "HEARD", "HEART", "HEARTS", "HEAT", "HEATED", "HEATER", "HEATH", "HEAVEN", "HEAVY", "HEBREW", "HEEL", "HEIGHT", "HELD", "HELEN", "HELENA", "HELLO", "HELMET", "HELP", "HELPED", "HELPS", "HENCE", "HENRY", "HER", "HERALD", "HERB", "HERBAL", "HERBS", "HERE", "HEREBY", "HEREIN", "HERO", "HEROES", "HEY", "HIDDEN", "HIDE", "HIGH", "HIGHER", "HIGHLY", "HIGHS", "HIKING", "HILL", "HILLS", "HILTON", "HIM", "HINDU", "HINT", "HINTS", "HIP", "HIRE", "HIRED", "HIRING", "HIS", "HIST", "HIT", "HITS", "HIV", "HOBBY", "HOCKEY", "HOLD", "HOLDEM", "HOLDER", "HOLDS", "HOLE", "HOLES", "HOLLOW", "HOLLY", "HOLMES", "HOLY", "HOME", "HOMES", "HON", "HONDA", "HONEST", "HONEY", "HONG", "HONOR", "HONORS", "HOOD", "HOOK", "HOP", "HOPE", "HOPED", "HOPES", "HOPING", "HORN", "HORROR", "HORSE", "HORSES", "HOSE", "HOST", "HOSTED", "HOSTEL", "HOSTS", "HOT", "HOTEL", "HOTELS", "HOUR", "HOURLY", "HOURS", "HOUSE", "HOUSES", "HOW", "HOWARD", "HOWTO", "HREF", "HRS", "HTML", "HTTP", "HUB", "HUDSON", "HUGE", "HUGH", "HUGHES", "HUGO", "HULL", "HUMAN", "HUMANS", "HUMOR", "HUNG", "HUNGER", "HUNGRY", "HUNT", "HUNTER", "HURT", "HWY", "HYBRID", "IAN", "IBM", "ICE", "ICON", "ICONS", "ICQ", "ICT", "IDAHO", "IDE", "IDEA", "IDEAL", "IDEAS", "IDLE", "IDOL", "IDS", "IEEE", "IGNORE", "III", "ILL", "IMAGE", "IMAGES", "IMG", "IMMUNE", "IMPACT", "IMPORT", "IMPOSE", "INBOX", "INC", "INCH", "INCHES", "INCL", "INCOME", "IND", "INDEED", "INDEX", "INDIA", "INDIAN", "INDIE", "INDOOR", "INF", "INFANT", "INFO", "INFORM", "ING", "INJURY", "INK", "INKJET", "INLINE", "INN", "INNER", "INNS", "INPUT", "INPUTS", "INS", "INSERT", "INSIDE", "INT", "INTAKE", "INTEL", "INTEND", "INTENT", "INTER", "INTL", "INTO", "INTRO", "INVEST", "INVITE", "ION", "IOWA", "IPAQ", "IPOD", "IPS", "IRA", "IRAN", "IRAQ", "IRAQI", "IRC", "IRISH", "IRON", "IRS", "ISA", "ISAAC", "ISBN", "ISLAM", "ISLAND", "ISLE", "ISO", "ISP", "ISRAEL", "ISSN", "ISSUE", "ISSUED", "ISSUES", "IST", "ITALIA", "ITALIC", "ITALY", "ITEM", "ITEMS", "ITS", "ITSELF", "ITUNES", "IVORY", "JACK", "JACKET", "JACKIE", "JACOB", "JADE", "JAGUAR", "JAIL", "JAKE", "JAM", "JAMES", "JAMIE", "JAN", "JANE", "JANET", "JAPAN", "JAR", "JASON", "JAVA", "JAY", "JAZZ", "JEAN", "JEANS", "JEEP", "JEFF", "JENNY", "JEREMY", "JERRY", "JERSEY", "JESSE", "JESUS", "JET", "JETS", "JEWEL", "JEWISH", "JEWS", "JILL", "JIM", "JIMMY", "JOAN", "JOB", "JOBS", "JOE", "JOEL", "JOHN", "JOHNNY", "JOHNS", "JOIN", "JOINED", "JOINS", "JOINT", "JOKE", "JOKES", "JON", "JONES", "JORDAN", "JOSE", "JOSEPH", "JOSH", "JOSHUA", "JOY", "JOYCE", "JPEG", "JPG", "JUAN", "JUDGE", "JUDGES", "JUDY", "JUICE", "JUL", "JULIA", "JULIAN", "JULIE", "JULY", "JUMP", "JUN", "JUNE", "JUNGLE", "JUNIOR", "JUNK", "JURY", "JUST", "JUSTIN", "JVC", "KAI", "KANSAS", "KAREN", "KARL", "KARMA", "KATE", "KATHY", "KATIE", "KAY", "KDE", "KEEN", "KEEP", "KEEPS", "KEITH", "KELKOO", "KELLY", "KEN", "KENNY", "KENO", "KENT", "KENYA", "KEPT", "KERNEL", "KERRY", "KEVIN", "KEY", "KEYS", "KICK", "KID", "KIDNEY", "KIDS", "KIJIJI", "KILL", "KILLED", "KILLER", "KILLS", "KIM", "KINASE", "KIND", "KINDA", "KINDS", "KING", "KINGS", "KIRK", "KISS", "KIT", "KITS", "KITTY", "KLEIN", "KNEE", "KNEW", "KNIFE", "KNIGHT", "KNIT", "KNIVES", "KNOCK", "KNOW", "KNOWN", "KNOWS", "KODAK", "KONG", "KOREA", "KOREAN", "KRUGER", "KURT", "KUWAIT", "KYLE", "LAB", "LABEL", "LABELS", "LABOR", "LABOUR", "LABS", "LACE", "LACK", "LADDER", "LADEN", "LADIES", "LADY", "LAID", "LAKE", "LAKES", "LAMB", "LAMBDA", "LAMP", "LAMPS", "LAN", "LANCE", "LAND", "LANDS", "LANE", "LANES", "LANG", "LANKA", "LAOS", "LAP", "LAPTOP", "LARGE", "LARGER", "LARRY", "LAS", "LASER", "LAST", "LAT", "LATE", "LATELY", "LATER", "LATEST", "LATEX", "LATIN", "LATINA", "LATINO", "LATTER", "LATVIA", "LAUGH", "LAUNCH", "LAURA", "LAUREN", "LAW", "LAWN", "LAWS", "LAWYER", "LAY", "LAYER", "LAYERS", "LAYOUT", "LAZY", "LBS", "LCD", "LEAD", "LEADER", "LEADS", "LEAF", "LEAGUE", "LEAN", "LEARN", "LEASE", "LEAST", "LEAVE", "LEAVES", "LED", "LEE", "LEEDS", "LEFT", "LEG", "LEGACY", "LEGAL", "LEGEND", "LEGS", "LEMON", "LEN", "LENDER", "LENGTH", "LENS", "LENSES", "LEO", "LEON", "LEONE", "LES", "LESLIE", "LESS", "LESSER", "LESSON", "LET", "LETS", "LETTER", "LEU", "LEVEL", "LEVELS", "LEVY", "LEWIS", "LEXUS", "LIABLE", "LIB", "LIBS", "LID", "LIE", "LIES", "LIFE", "LIFT", "LIGHT", "LIGHTS", "LIKE", "LIKED", "LIKELY", "LIKES", "LIL", "LIME", "LIMIT", "LIMITS", "LINDA", "LINE", "LINEAR", "LINED", "LINES", "LINK", "LINKED", "LINKS", "LINUX", "LION", "LIONS", "LIP", "LIPS", "LIQUID", "LISA", "LIST", "LISTED", "LISTEN", "LISTS", "LIT", "LITE", "LITTLE", "LIVE", "LIVED", "LIVER", "LIVES", "LIVING", "LIZ", "LLC", "LLOYD", "LLP", "LOAD", "LOADED", "LOADS", "LOAN", "LOANS", "LOBBY", "LOC", "LOCAL", "LOCALE", "LOCATE", "LOCK", "LOCKED", "LOCKS", "LODGE", "LOG", "LOGAN", "LOGGED", "LOGIC", "LOGIN", "LOGO", "LOGOS", "LOGS", "LOL", "LONDON", "LONE", "LONELY", "LONG", "LONGER", "LOOK", "LOOKED", "LOOKS", "LOOKUP", "LOOP", "LOOPS", "LOOSE", "LOPEZ", "LORD", "LOS", "LOSE", "LOSING", "LOSS", "LOSSES", "LOST", "LOT", "LOTS", "LOTUS", "LOU", "LOUD", "LOUIS", "LOUISE", "LOUNGE", "LOVE", "LOVED", "LOVELY", "LOVER", "LOVERS", "LOVES", "LOVING", "LOW", "LOWER", "LOWEST", "LOWS", "LTD", "LUCAS", "LUCIA", "LUCK", "LUCKY", "LUCY", "LUIS", "LUKE", "LUNCH", "LUNG", "LUTHER", "LUXURY", "LYCOS", "LYING", "LYNN", "LYRIC", "LYRICS", "MAC", "MACRO", "MAD", "MADE", "MADRID", "MAE", "MAG", "MAGIC", "MAGNET", "MAI", "MAIDEN", "MAIL", "MAILED", "MAILS", "MAILTO", "MAIN", "MAINE", "MAINLY", "MAJOR", "MAKE", "MAKER", "MAKERS", "MAKES", "MAKEUP", "MAKING", "MALAWI", "MALE", "MALES", "MALI", "MALL", "MALTA", "MAMBO", "MAN", "MANAGE", "MANGA", "MANNER", "MANOR", "MANUAL", "MANY", "MAP", "MAPLE", "MAPS", "MAR", "MARBLE", "MARC", "MARCH", "MARCO", "MARCUS", "MARDI", "MARGIN", "MARIA", "MARIAH", "MARIE", "MARINA", "MARINE", "MARIO", "MARION", "MARK", "MARKED", "MARKER", "MARKET", "MARKS", "MARS", "MARSH", "MART", "MARTHA", "MARTIN", "MARVEL", "MARY", "MAS", "MASK", "MASON", "MASS", "MASTER", "MAT", "MATCH", "MATE", "MATH", "MATING", "MATRIX", "MATS", "MATT", "MATTER", "MATURE", "MAUI", "MAX", "MAY", "MAYBE", "MAYOR", "MAZDA", "MBA", "MEAL", "MEALS", "MEAN", "MEANS", "MEANT", "MEAT", "MED", "MEDAL", "MEDIA", "MEDIAN", "MEDIUM", "MEET", "MEETS", "MEETUP", "MEGA", "MEL", "MEM", "MEMBER", "MEMO", "MEMORY", "MEN", "MENS", "MENT", "MENTAL", "MENTOR", "MENU", "MENUS", "MERCY", "MERE", "MERELY", "MERGE", "MERGER", "MERIT", "MERRY", "MESA", "MESH", "MESS", "MET", "META", "METAL", "METALS", "METER", "METERS", "METHOD", "METRES", "METRIC", "METRO", "MEXICO", "MEYER", "MHZ", "MIA", "MIAMI", "MIC", "MICE", "MICHEL", "MICRO", "MID", "MIDDLE", "MIDI", "MIGHT", "MIGHTY", "MIKE", "MIL", "MILAN", "MILD", "MILE", "MILES", "MILK", "MILL", "MILLER", "MILLS", "MILTON", "MIME", "MIN", "MIND", "MINDS", "MINE", "MINES", "MINI", "MINING", "MINOR", "MINS", "MINT", "MINUS", "MINUTE", "MIRROR", "MISC", "MISS", "MISSED", "MIT", "MIX", "MIXED", "MIXER", "MIXING", "MLB", "MLS", "MOBILE", "MOD", "MODE", "MODEL", "MODELS", "MODEM", "MODEMS", "MODERN", "MODES", "MODIFY", "MODS", "MODULE", "MOLD", "MOM", "MOMENT", "MOMS", "MON", "MONACO", "MONDAY", "MONEY", "MONICA", "MONKEY", "MONO", "MONROE", "MONTE", "MONTH", "MONTHS", "MOOD", "MOON", "MOORE", "MORAL", "MORE", "MORGAN", "MORRIS", "MOSCOW", "MOSES", "MOSS", "MOST", "MOSTLY", "MOTEL", "MOTELS", "MOTHER", "MOTION", "MOTOR", "MOTORS", "MOUNT", "MOUNTS", "MOUSE", "MOUTH", "MOVE", "MOVED", "MOVERS", "MOVES", "MOVIE", "MOVIES", "MOVING", "MPEG", "MPEGS", "MPG", "MPH", "MRNA", "MRS", "MSG", "MSGID", "MSGSTR", "MSIE", "MSN", "MTV", "MUCH", "MUD", "MUG", "MULTI", "MUMBAI", "MUNICH", "MURDER", "MURPHY", "MURRAY", "MUSCLE", "MUSEUM", "MUSIC", "MUSLIM", "MUST", "MUTUAL", "MUZE", "MYERS", "MYRTLE", "MYSELF", "MYSQL", "MYTH", "NAIL", "NAILS", "NAKED", "NAM", "NAME", "NAMED", "NAMELY", "NAMES", "NANCY", "NANO", "NAPLES", "NARROW", "NASA", "NASCAR", "NASDAQ", "NASTY", "NAT", "NATHAN", "NATION", "NATIVE", "NATO", "NATURE", "NAV", "NAVAL", "NAVY", "NBA", "NBC", "NCAA", "NEAR", "NEARBY", "NEARLY", "NEC", "NECK", "NEED", "NEEDED", "NEEDLE", "NEEDS", "NEIL", "NELSON", "NEO", "NEON", "NEPAL", "NERVE", "NEST", "NESTED", "NET", "NEURAL", "NEVADA", "NEVER", "NEW", "NEWARK", "NEWBIE", "NEWER", "NEWEST", "NEWLY", "NEWMAN", "NEWS", "NEWTON", "NEXT", "NEXTEL", "NFL", "NHL", "NHS", "NICE", "NICK", "NICKEL", "NICOLE", "NIGER", "NIGHT", "NIGHTS", "NIKE", "NIKON", "NIL", "NINE", "NISSAN", "NOBLE", "NOBODY", "NODE", "NODES", "NOISE", "NOKIA", "NON", "NONE", "NOON", "NOR", "NORM", "NORMAL", "NORMAN", "NORTH", "NORTON", "NORWAY", "NOSE", "NOT", "NOTE", "NOTED", "NOTES", "NOTICE", "NOTIFY", "NOTION", "NOTRE", "NOV", "NOVA", "NOVEL", "NOVELS", "NOW", "NSW", "NTSC", "NUDIST", "NUKE", "NULL", "NUMBER", "NURSE", "NURSES", "NUT", "NUTS", "NUTTEN", "NVIDIA", "NYC", "NYLON", "OAK", "OAKS", "OASIS", "OBJ", "OBJECT", "OBTAIN", "OCCUR", "OCCURS", "OCEAN", "OCLC", "OCT", "ODD", "ODDS", "OECD", "OEM", "OFF", "OFFER", "OFFERS", "OFFICE", "OFFSET", "OFTEN", "OHIO", "OIL", "OILS", "OKAY", "OLD", "OLDER", "OLDEST", "OLIVE", "OLIVER", "OMAHA", "OMAN", "OMEGA", "ONCE", "ONE", "ONES", "ONION", "ONLINE", "ONLY", "ONS", "ONTO", "OOO", "OOPS", "OPEN", "OPENED", "OPENS", "OPERA", "OPT", "OPTICS", "OPTION", "ORACLE", "ORAL", "ORANGE", "ORBIT", "ORDER", "ORDERS", "OREGON", "ORG", "ORGAN", "ORIGIN", "OSCAR", "OTHER", "OTHERS", "OTTAWA", "OUGHT", "OUR", "OURS", "OUT", "OUTER", "OUTLET", "OUTPUT", "OVAL", "OVEN", "OVER", "OWEN", "OWN", "OWNED", "OWNER", "OWNERS", "OWNS", "OXFORD", "OXIDE", "OXYGEN", "OZONE", "PAC", "PACE", "PACK", "PACKED", "PACKET", "PACKS", "PAD", "PADS", "PAGE", "PAGES", "PAID", "PAIN", "PAINT", "PAIR", "PAIRS", "PAL", "PALACE", "PALE", "PALM", "PALMER", "PAM", "PAMELA", "PAN", "PANAMA", "PANEL", "PANELS", "PANIC", "PANTS", "PAPER", "PAPERS", "PAPUA", "PAR", "PARA", "PARADE", "PARCEL", "PARENT", "PARIS", "PARISH", "PARK", "PARKER", "PARKS", "PART", "PARTLY", "PARTS", "PARTY", "PAS", "PASO", "PASS", "PASSED", "PASSES", "PAST", "PASTA", "PASTE", "PASTOR", "PAT", "PATCH", "PATENT", "PATH", "PATHS", "PATIO", "PATROL", "PAUL", "PAXIL", "PAY", "PAYDAY", "PAYING", "PAYPAL", "PAYS", "PCI", "PCS", "PCT", "PDA", "PDAS", "PDF", "PDT", "PEACE", "PEAK", "PEARL", "PEAS", "PEE", "PEEING", "PEER", "PEERS", "PEN", "PENCIL", "PENN", "PENNY", "PENS", "PEOPLE", "PEPPER", "PER", "PERIOD", "PERL", "PERMIT", "PERRY", "PERSON", "PERTH", "PERU", "PEST", "PET", "PETE", "PETER", "PETITE", "PETS", "PGP", "PHASE", "PHASES", "PHD", "PHI", "PHIL", "PHILIP", "PHONE", "PHONES", "PHOTO", "PHOTOS", "PHP", "PHPBB", "PHRASE", "PHYS", "PIANO", "PIC", "PICK", "PICKED", "PICKS", "PICKUP", "PICNIC", "PICS", "PIE", "PIECE", "PIECES", "PIERCE", "PIERRE", "PIG", "PIKE", "PILL", "PILLOW", "PILLS", "PILOT", "PIN", "PINE", "PING", "PINK", "PINS", "PIPE", "PIPES", "PIT", "PITCH", "PIX", "PIXEL", "PIXELS", "PIZZA", "PLACE", "PLACED", "PLACES", "PLAIN", "PLAINS", "PLAN", "PLANE", "PLANES", "PLANET", "PLANS", "PLANT", "PLANTS", "PLASMA", "PLATE", "PLATES", "PLAY", "PLAYED", "PLAYER", "PLAYS", "PLAZA", "PLC", "PLEASE", "PLEDGE", "PLENTY", "PLOT", "PLOTS", "PLUG", "PLUGIN", "PLUS", "PMC", "PMID", "POCKET", "POD", "POEM", "POEMS", "POET", "POETRY", "POINT", "POINTS", "POISON", "POKER", "POLAND", "POLAR", "POLE", "POLICE", "POLICY", "POLISH", "POLL", "POLLS", "POLO", "POLY", "POND", "POOL", "POOLS", "POOR", "POP", "POPE", "POR", "PORK", "PORT", "PORTAL", "PORTER", "PORTS", "POS", "POSE", "POSING", "POST", "POSTAL", "POSTED", "POSTER", "POSTS", "POT", "POTATO", "POTTER", "POUND", "POUNDS", "POUR", "POWDER", "POWELL", "POWER", "POWERS", "PPC", "PPM", "PRAGUE", "PRAISE", "PRAY", "PRAYER", "PRE", "PREFER", "PREFIX", "PREP", "PRESS", "PRETTY", "PREV", "PRICE", "PRICED", "PRICES", "PRIDE", "PRIEST", "PRIME", "PRINCE", "PRINT", "PRINTS", "PRIOR", "PRISON", "PRIX", "PRIZE", "PRIZES", "PRO", "PROBE", "PROC", "PROFIT", "PROMO", "PROMPT", "PROOF", "PROPER", "PROS", "PROT", "PROUD", "PROVE", "PROVED", "PROVEN", "PROXY", "PROZAC", "PSI", "PSP", "PST", "PTS", "PTY", "PUB", "PUBLIC", "PUBMED", "PUBS", "PUERTO", "PULL", "PULLED", "PULSE", "PUMP", "PUMPS", "PUNCH", "PUNK", "PUPILS", "PUPPY", "PURE", "PURPLE", "PURSE", "PURSUE", "PUSH", "PUSHED", "PUT", "PUTS", "PUZZLE", "PVC", "PYTHON", "QATAR", "QLD", "QTY", "QUAD", "QUE", "QUEBEC", "QUEEN", "QUEENS", "QUERY", "QUEST", "QUEUE", "QUI", "QUICK", "QUIET", "QUILT", "QUIT", "QUITE", "QUIZ", "QUOTE", "QUOTED", "QUOTES", "RABBIT", "RACE", "RACES", "RACHEL", "RACIAL", "RACING", "RACK", "RACKS", "RADAR", "RADIO", "RADIOS", "RADIUS", "RAGE", "RAID", "RAIL", "RAIN", "RAISE", "RAISED", "RAISES", "RALLY", "RALPH", "RAM", "RAN", "RANCH", "RAND", "RANDOM", "RANDY", "RANGE", "RANGER", "RANGES", "RANK", "RANKED", "RANKS", "RAP", "RAPID", "RAPIDS", "RARE", "RARELY", "RAT", "RATE", "RATED", "RATES", "RATHER", "RATING", "RATIO", "RATIOS", "RATS", "RAW", "RAY", "RAYS", "RCA", "REACH", "READ", "READER", "READS", "READY", "REAL", "REALLY", "REALM", "REALTY", "REAR", "REASON", "REBATE", "REBEL", "REC", "RECALL", "RECENT", "RECIPE", "RECORD", "RED", "REDEEM", "REDUCE", "REED", "REEF", "REEL", "REF", "REFER", "REFERS", "REFINE", "REFORM", "REFUND", "REFUSE", "REG", "REGARD", "REGGAE", "REGIME", "REGION", "REHAB", "REID", "REJECT", "RELATE", "RELAX", "RELAY", "RELIEF", "RELOAD", "RELY", "REMAIN", "REMARK", "REMEDY", "REMIND", "REMIX", "REMOTE", "REMOVE", "RENDER", "RENEW", "RENO", "RENT", "RENTAL", "REP", "REPAIR", "REPEAT", "REPLY", "REPORT", "RES", "RESCUE", "RESET", "RESIST", "RESORT", "REST", "RESULT", "RESUME", "RETAIL", "RETAIN", "RETRO", "RETURN", "REV", "REVEAL", "REVIEW", "REWARD", "RFC", "RHODE", "RHYTHM", "RIBBON", "RICA", "RICE", "RICH", "RICK", "RICKY", "RICO", "RID", "RIDE", "RIDER", "RIDERS", "RIDES", "RIDGE", "RIDING", "RIGHT", "RIGHTS", "RIM", "RING", "RINGS", "RIO", "RIP", "RIPE", "RISE", "RISING", "RISK", "RISKS", "RIVER", "RIVERS", "RNA", "ROAD", "ROADS", "ROB", "ROBBIE", "ROBERT", "ROBIN", "ROBOT", "ROBOTS", "ROBUST", "ROCK", "ROCKET", "ROCKS", "ROCKY", "ROD", "ROGER", "ROGERS", "ROLAND", "ROLE", "ROLES", "ROLL", "ROLLED", "ROLLER", "ROLLS", "ROM", "ROMAN", "ROME", "RON", "RONALD", "ROOF", "ROOM", "ROOMS", "ROOT", "ROOTS", "ROPE", "ROSA", "ROSE", "ROSES", "ROSS", "ROSTER", "ROTARY", "ROUGE", "ROUGH", "ROUND", "ROUNDS", "ROUTE", "ROUTER", "ROUTES", "ROVER", "ROW", "ROWS", "ROY", "ROYAL", "RPG", "RPM", "RRP", "RSS", "RUBBER", "RUBY", "RUG", "RUGBY", "RUGS", "RULE", "RULED", "RULES", "RULING", "RUN", "RUNNER", "RUNS", "RURAL", "RUSH", "RUSSIA", "RUTH", "RWANDA", "RYAN", "SACRED", "SAD", "SADDAM", "SAFARI", "SAFE", "SAFELY", "SAFER", "SAFETY", "SAGE", "SAGEM", "SAID", "SAIL", "SAINT", "SAINTS", "SAKE", "SALAD", "SALARY", "SALE", "SALEM", "SALES", "SALLY", "SALMON", "SALON", "SALT", "SAM", "SAMBA", "SAME", "SAMOA", "SAMPLE", "SAMUEL", "SAN", "SAND", "SANDRA", "SANDY", "SANS", "SANTA", "SANYO", "SAO", "SAP", "SARA", "SARAH", "SAS", "SAT", "SATIN", "SATURN", "SAUCE", "SAUDI", "SAVAGE", "SAVE", "SAVED", "SAVER", "SAVES", "SAVING", "SAW", "SAY", "SAYING", "SAYS", "SBJCT", "SCALE", "SCALES", "SCAN", "SCARED", "SCARY", "SCENE", "SCENES", "SCENIC", "SCHEMA", "SCHEME", "SCHOOL", "SCI", "SCOOP", "SCOPE", "SCORE", "SCORED", "SCORES", "SCOTIA", "SCOTT", "SCOUT", "SCREEN", "SCREW", "SCRIPT", "SCROLL", "SCSI", "SCUBA", "SEA", "SEAL", "SEALED", "SEAN", "SEARCH", "SEAS", "SEASON", "SEAT", "SEATS", "SEC", "SECOND", "SECRET", "SECTOR", "SECURE", "SEE", "SEED", "SEEDS", "SEEING", "SEEK", "SEEKER", "SEEKS", "SEEM", "SEEMED", "SEEMS", "SEEN", "SEES", "SEGA", "SELECT", "SELF", "SELL", "SELLER", "SELLS", "SEMI", "SEN", "SENATE", "SEND", "SENDER", "SENDS", "SENIOR", "SENSE", "SENSOR", "SENT", "SEO", "SEP", "SEPT", "SEQ", "SER", "SERBIA", "SERIAL", "SERIES", "SERUM", "SERVE", "SERVED", "SERVER", "SERVES", "SET", "SETS", "SETTLE", "SETUP", "SEVEN", "SEVERE", "SEWING", "SEXUAL", "SHADE", "SHADES", "SHADOW", "SHAFT", "SHAKE", "SHALL", "SHAME", "SHAPE", "SHAPED", "SHAPES", "SHARE", "SHARED", "SHARES", "SHARK", "SHARON", "SHARP", "SHAVED", "SHAW", "SHE", "SHED", "SHEEP", "SHEER", "SHEET", "SHEETS", "SHELF", "SHELL", "SHIELD", "SHIFT", "SHINE", "SHIP", "SHIPS", "SHIRT", "SHIRTS", "SHOCK", "SHOE", "SHOES", "SHOOT", "SHOP", "SHOPS", "SHORE", "SHORT", "SHORTS", "SHOT", "SHOTS", "SHOULD", "SHOW", "SHOWED", "SHOWER", "SHOWN", "SHOWS", "SHUT", "SIC", "SICK", "SIDE", "SIDES", "SIE", "SIERRA", "SIG", "SIGHT", "SIGMA", "SIGN", "SIGNAL", "SIGNED", "SIGNS", "SIGNUP", "SILENT", "SILK", "SILLY", "SILVER", "SIM", "SIMON", "SIMPLE", "SIMPLY", "SIMS", "SIN", "SINCE", "SING", "SINGER", "SINGH", "SINGLE", "SINK", "SIP", "SIR", "SISTER", "SIT", "SITE", "SITES", "SIX", "SIXTH", "SIZE", "SIZED", "SIZES", "SKI", "SKIING", "SKILL", "SKILLS", "SKIN", "SKINS", "SKIP", "SKIRT", "SKIRTS", "SKU", "SKY", "SKYPE", "SLAVE", "SLEEP", "SLEEPS", "SLEEVE", "SLIDE", "SLIDES", "SLIGHT", "SLIM", "SLIP", "SLOPE", "SLOT", "SLOTS", "SLOVAK", "SLOW", "SLOWLY", "SMALL", "SMART", "SMELL", "SMILE", "SMITH", "SMOKE", "SMOOTH", "SMS", "SMTP", "SNAKE", "SNAP", "SNOW", "SOA", "SOAP", "SOC", "SOCCER", "SOCIAL", "SOCKET", "SOCKS", "SODIUM", "SOFA", "SOFT", "SOIL", "SOL", "SOLAR", "SOLD", "SOLE", "SOLELY", "SOLID", "SOLO", "SOLVE", "SOLVED", "SOMA", "SOME", "SON", "SONG", "SONGS", "SONIC", "SONS", "SONY", "SOON", "SORRY", "SORT", "SORTED", "SORTS", "SOUGHT", "SOUL", "SOULS", "SOUND", "SOUNDS", "SOUP", "SOURCE", "SOUTH", "SOVIET", "SOX", "SPA", "SPACE", "SPACES", "SPAIN", "SPAM", "SPAN", "SPANK", "SPARC", "SPARE", "SPAS", "SPEAK", "SPEAKS", "SPEARS", "SPEC", "SPECS", "SPEECH", "SPEED", "SPEEDS", "SPELL", "SPEND", "SPENT", "SPERM", "SPHERE", "SPICE", "SPIDER", "SPIES", "SPIN", "SPINE", "SPIRIT", "SPLIT", "SPOKE", "SPOKEN", "SPORT", "SPORTS", "SPOT", "SPOTS", "SPOUSE", "SPRAY", "SPREAD", "SPRING", "SPRINT", "SPY", "SQL", "SQUAD", "SQUARE", "SRC", "SRI", "SSL", "STABLE", "STACK", "STAFF", "STAGE", "STAGES", "STAKE", "STAMP", "STAMPS", "STAN", "STAND", "STANDS", "STAR", "STARS", "START", "STARTS", "STAT", "STATE", "STATED", "STATES", "STATIC", "STATS", "STATUS", "STAY", "STAYED", "STAYS", "STD", "STE", "STEADY", "STEAL", "STEAM", "STEEL", "STEM", "STEP", "STEPS", "STEREO", "STEVE", "STEVEN", "STICK", "STICKS", "STICKY", "STILL", "STOCK", "STOCKS", "STOLEN", "STONE", "STONES", "STOOD", "STOP", "STOPS", "STORE", "STORED", "STORES", "STORM", "STORY", "STR", "STRAIN", "STRAND", "STRAP", "STREAM", "STREET", "STRESS", "STRICT", "STRIKE", "STRING", "STRIP", "STRIPS", "STROKE", "STRONG", "STRUCK", "STRUCT", "STUART", "STUCK", "STUD", "STUDIO", "STUDY", "STUFF", "STUPID", "STYLE", "STYLES", "STYLUS", "SUB", "SUBARU", "SUBMIT", "SUBTLE", "SUCH", "SUDAN", "SUDDEN", "SUE", "SUFFER", "SUGAR", "SUIT", "SUITE", "SUITED", "SUITES", "SUITS", "SUM", "SUMMER", "SUMMIT", "SUN", "SUNDAY", "SUNNY", "SUNSET", "SUPER", "SUPERB", "SUPPLY", "SUR", "SURE", "SURELY", "SURF", "SURGE", "SURREY", "SURVEY", "SUSAN", "SUSE", "SUSSEX", "SUZUKI", "SWAP", "SWEDEN", "SWEET", "SWIFT", "SWIM", "SWING", "SWISS", "SWITCH", "SWORD", "SYDNEY", "SYMBOL", "SYNC", "SYNTAX", "SYRIA", "SYS", "SYSTEM", "TAB", "TABLE", "TABLES", "TABLET", "TABS", "TACKLE", "TAG", "TAGGED", "TAGS", "TAHOE", "TAIL", "TAIWAN", "TAKE", "TAKEN", "TAKES", "TAKING", "TALE", "TALENT", "TALES", "TALK", "TALKED", "TALKS", "TALL", "TAMIL", "TAMPA", "TAN", "TANK", "TANKS", "TAP", "TAPE", "TAPES", "TAR", "TARGET", "TARIFF", "TASK", "TASKS", "TASTE", "TATTOO", "TAUGHT", "TAX", "TAXES", "TAXI", "TAYLOR", "TBA", "TCP", "TEA", "TEACH", "TEAM", "TEAMS", "TEAR", "TEARS", "TECH", "TECHNO", "TED", "TEDDY", "TEE", "TEEN", "TEENS", "TEETH", "TEL", "TELL", "TELLS", "TEMP", "TEMPLE", "TEN", "TENANT", "TEND", "TENDER", "TENNIS", "TENT", "TERM", "TERMS", "TERROR", "TERRY", "TEST", "TESTED", "TESTS", "TEX", "TEXAS", "TEXT", "TEXTS", "TFT", "TGP", "THAI", "THAN", "THANK", "THANKS", "THAT", "THATS", "THE", "THEE", "THEFT", "THEHUN", "THEIR", "THEM", "THEME", "THEMES", "THEN", "THEORY", "THERE", "THESE", "THESIS", "THETA", "THEY", "THICK", "THIN", "THING", "THINGS", "THINK", "THINKS", "THIRD", "THIRTY", "THIS", "THOMAS", "THONG", "THONGS", "THOSE", "THOU", "THOUGH", "THREAD", "THREAT", "THREE", "THROAT", "THROW", "THROWN", "THROWS", "THRU", "THU", "THUMB", "THUMBS", "THUS", "THY", "TICKET", "TIDE", "TIE", "TIED", "TIER", "TIES", "TIGER", "TIGERS", "TIGHT", "TIL", "TILE", "TILES", "TILL", "TIM", "TIMBER", "TIME", "TIMELY", "TIMER", "TIMES", "TIMING", "TIN", "TINY", "TION", "TIONS", "TIP", "TIPS", "TIRE", "TIRED", "TIRES", "TISSUE", "TITANS", "TITLE", "TITLED", "TITLES", "TITTEN", "TMP", "TOBAGO", "TODAY", "TODD", "TOE", "TOILET", "TOKEN", "TOKYO", "TOLD", "TOLL", "TOM", "TOMATO", "TOMMY", "TON", "TONE", "TONER", "TONES", "TONGUE", "TONS", "TONY", "TOO", "TOOK", "TOOL", "TOOLS", "TOOTH", "TOP", "TOPIC", "TOPICS", "TOPS", "TOTAL", "TOTALS", "TOUCH", "TOUGH", "TOUR", "TOURS", "TOWARD", "TOWER", "TOWERS", "TOWN", "TOWNS", "TOXIC", "TOY", "TOYOTA", "TOYS", "TRACE", "TRACK", "TRACKS", "TRACT", "TRACY", "TRADE", "TRADER", "TRADES", "TRAIL", "TRAILS", "TRAIN", "TRAINS", "TRANCE", "TRANS", "TRAP", "TRASH", "TRAUMA", "TRAVEL", "TRAVIS", "TRAY", "TREAT", "TREATY", "TREE", "TREES", "TREK", "TREMBL", "TREND", "TRENDS", "TREO", "TRI", "TRIAL", "TRIALS", "TRIBAL", "TRIBE", "TRIBES", "TRICK", "TRICKS", "TRIED", "TRIES", "TRIM", "TRIO", "TRIP", "TRIPLE", "TRIPS", "TRIVIA", "TROOPS", "TROUT", "TROY", "TRUCK", "TRUCKS", "TRUE", "TRULY", "TRUNK", "TRUST", "TRUSTS", "TRUTH", "TRY", "TRYING", "TUB", "TUBE", "TUBES", "TUCSON", "TUE", "TULSA", "TUMOR", "TUNE", "TUNER", "TUNES", "TUNING", "TUNNEL", "TURBO", "TURKEY", "TURN", "TURNED", "TURNER", "TURNS", "TURTLE", "TVS", "TWELVE", "TWENTY", "TWICE", "TWIKI", "TWIN", "TWINS", "TWIST", "TWO", "TYLER", "TYPE", "TYPES", "TYPING", "UGANDA", "UGLY", "ULTRA", "ULTRAM", "UNA", "UNABLE", "UNCLE", "UND", "UNDER", "UNDO", "UNE", "UNI", "UNION", "UNIONS", "UNIQUE", "UNIT", "UNITED", "UNITS", "UNITY", "UNIV", "UNIX", "UNLESS", "UNLIKE", "UNLOCK", "UNTIL", "UNTO", "UNWRAP", "UPC", "UPDATE", "UPLOAD", "UPON", "UPPER", "UPS", "UPSET", "URBAN", "URGE", "URGENT", "URI", "URL", "URLS", "URW", "USA", "USAGE", "USB", "USC", "USD", "USDA", "USE", "USED", "USEFUL", "USER", "USERS", "USES", "USGS", "USING", "USPS", "USR", "USUAL", "UTAH", "UTC", "UTILS", "VACUUM", "VAL", "VALID", "VALIUM", "VALLEY", "VALUE", "VALUED", "VALUES", "VALVE", "VALVES", "VAN", "VAR", "VARIED", "VARIES", "VARY", "VAST", "VAT", "VAULT", "VCR", "VECTOR", "VEGAS", "VELVET", "VENDOR", "VENICE", "VENUE", "VENUES", "VER", "VERBAL", "VERDE", "VERIFY", "VERNON", "VERSE", "VERSUS", "VERTEX", "VERY", "VESSEL", "VHS", "VIA", "VIC", "VICE", "VICTIM", "VICTOR", "VID", "VIDEO", "VIDEOS", "VIDS", "VIENNA", "VIEW", "VIEWED", "VIEWER", "VIEWS", "VII", "VIII", "VIKING", "VILLA", "VILLAS", "VINYL", "VIOLIN", "VIP", "VIRAL", "VIRGIN", "VIRTUE", "VIRUS", "VISA", "VISION", "VISIT", "VISITS", "VISTA", "VISUAL", "VITAL", "VOCAL", "VOCALS", "VOICE", "VOICES", "VOID", "VOIP", "VOL", "VOLT", "VOLUME", "VOLVO", "VON", "VOTE", "VOTED", "VOTERS", "VOTES", "VOTING", "VOYUER", "VPN", "VSNET", "WAGE", "WAGES", "WAGNER", "WAGON", "WAIT", "WAIVER", "WAKE", "WAL", "WALES", "WALK", "WALKED", "WALKER", "WALKS", "WALL", "WALLET", "WALLS", "WALNUT", "WALT", "WALTER", "WAN", "WANNA", "WANT", "WANTED", "WANTS", "WAR", "WARD", "WARE", "WARM", "WARNED", "WARNER", "WARREN", "WARS", "WAS", "WASH", "WASHER", "WASTE", "WATCH", "WATER", "WATERS", "WATSON", "WATT", "WATTS", "WAV", "WAVE", "WAVES", "WAX", "WAY", "WAYNE", "WAYS", "WEAK", "WEALTH", "WEAPON", "WEAR", "WEB", "WEBCAM", "WEBLOG", "WED", "WEED", "WEEK", "WEEKLY", "WEEKS", "WEIGHT", "WEIRD", "WELL", "WELLS", "WELSH", "WENDY", "WENT", "WERE", "WESLEY", "WEST", "WET", "WHALE", "WHAT", "WHATS", "WHEAT", "WHEEL", "WHEELS", "WHEN", "WHERE", "WHICH", "WHILE", "WHILST", "WHITE", "WHO", "WHOLE", "WHOM", "WHOSE", "WHY", "WICKED", "WIDE", "WIDELY", "WIDER", "WIDTH", "WIFE", "WIFI", "WIKI", "WILD", "WILEY", "WILL", "WILLOW", "WILSON", "WIN", "WIND", "WINDOW", "WINDS", "WINE", "WINES", "WING", "WINGS", "WINNER", "WINS", "WINTER", "WIRE", "WIRED", "WIRES", "WIRING", "WISDOM", "WISE", "WISH", "WISHES", "WIT", "WITCH", "WITH", "WITHIN", "WIVES", "WIZARD", "WMA", "WOLF", "WOMAN", "WOMEN", "WOMENS", "WON", "WONDER", "WOOD", "WOODEN", "WOODS", "WOOL", "WORD", "WORDS", "WORK", "WORKED", "WORKER", "WORKS", "WORLD", "WORLDS", "WORM", "WORN", "WORRY", "WORSE", "WORST", "WORTH", "WORTHY", "WOULD", "WOUND", "WOW", "WRAP", "WRIGHT", "WRIST", "WRITE", "WRITER", "WRITES", "WRONG", "WROTE", "WTO", "WWW", "XANAX", "XBOX", "XEROX", "XHTML", "XML", "YACHT", "YAHOO", "YALE", "YAMAHA", "YANG", "YARD", "YARDS", "YARN", "YEA", "YEAH", "YEAR", "YEARLY", "YEARS", "YEAST", "YELLOW", "YEMEN", "YEN", "YES", "YET", "YIELD", "YIELDS", "YOGA", "YORK", "YOU", "YOUNG", "YOUR", "YOURS", "YOUTH", "YRS", "YUKON", "ZAMBIA", "ZDNET", "ZEN", "ZERO", "ZINC", "ZIP", "ZOLOFT", "ZONE", "ZONES", "ZONING", "ZOO", "ZOOM", "ZOPE", "ZSHOPS", "ZUM", "ZUS"]);
var VOWELS = { A:1, E:1, I:1, O:1, U:1 };
var KEYBOARD_ROWS = ["QWERTYUIOP", "ASDFGHJKL", "ZXCVBNM"];
var SECRET_CODE = "dkfkdkfjdjfj";
var COOLDOWN_MS = 10 * 60 * 1000;

var typedBuffer = "";
document.addEventListener("keydown", function (e) {
  if (e.key.length === 1) {
    typedBuffer = (typedBuffer + e.key.toLowerCase()).slice(-40);
    if (typedBuffer.indexOf(SECRET_CODE) !== -1) {
      typedBuffer = "";
      var enabled = localStorage.getItem("sixroll_unlimited") === "1";
      localStorage.setItem("sixroll_unlimited", enabled ? "0" : "1");
      updateUnlimitedUI();
      showToast(enabled ? "Test mode off" : "Test mode: unlimited rolls");
    }
  }
});

function updateUnlimitedUI() {
  var on = localStorage.getItem("sixroll_unlimited") === "1";
  document.getElementById("unlimitedBadge").style.display = on ? "inline-block" : "none";
}

function showToast(msg) {
  var t = document.getElementById("toast");
  t.textContent = msg;
  t.classList.add("show");
  setTimeout(function () { t.classList.remove("show"); }, 2200);
}

function getName() {
  return (localStorage.getItem("sixroll_name") || "").trim();
}

var nameInput = document.getElementById("nameInput");
nameInput.value = getName();
nameInput.addEventListener("input", function () {
  localStorage.setItem("sixroll_name", nameInput.value.trim());
});

function randLetter() {
  return String.fromCharCode(65 + Math.floor(Math.random() * 26));
}

function buildTiles() {
  var wrap = document.getElementById("tiles");
  wrap.innerHTML = "";
  for (var i = 0; i < 6; i++) {
    var d = document.createElement("div");
    d.className = "tile";
    d.id = "tile" + i;
    d.textContent = "";
    wrap.appendChild(d);
  }
}
buildTiles();

function revealTile(i, finalLetter) {
  return new Promise(function (resolve) {
    var el = document.getElementById("tile" + i);
    var spins = 8;
    var count = 0;
    var iv = setInterval(function () {
      el.textContent = randLetter();
      count++;
      if (count >= spins) {
        clearInterval(iv);
        el.textContent = finalLetter;
        el.classList.add("settled");
        resolve();
      }
    }, 45);
  });
}

// ---- Badge scoring ----

function longestRun(letters) {
  var best = 1, curAsc = 1, curDesc = 1;
  for (var i = 1; i < letters.length; i++) {
    var diff = letters[i].charCodeAt(0) - letters[i - 1].charCodeAt(0);
    if (diff === 1) { curAsc++; curDesc = 1; }
    else if (diff === -1) { curDesc++; curAsc = 1; }
    else { curAsc = 1; curDesc = 1; }
    best = Math.max(best, curAsc, curDesc);
  }
  return best;
}

function findWords(seq) {
  var found = [];
  for (var len = 6; len >= 3; len--) {
    for (var start = 0; start + len <= 6; start++) {
      var sub = seq.slice(start, start + len);
      if (WORDS.has(sub)) found.push({ word: sub, len: len });
    }
  }
  return found;
}

function keyboardBestLen(seq) {
  var best = 0;
  for (var r = 0; r < KEYBOARD_ROWS.length; r++) {
    var row = KEYBOARD_ROWS[r];
    var rowRev = row.split("").reverse().join("");
    for (var len = 4; len >= 3; len--) {
      for (var start = 0; start + len <= 6; start++) {
        var sub = seq.slice(start, start + len);
        if (row.indexOf(sub) !== -1 || rowRev.indexOf(sub) !== -1) {
          best = Math.max(best, len);
        }
      }
    }
  }
  return best;
}

function computeRoll(letters) {
  var seq = letters.join("");
  var badges = [];
  var supporting = [];

  var words = findWords(seq);
  if (words.length > 0) {
    var best = words[0];
    var epMap = { 6: 2500, 5: 500, 4: 120, 3: 25 };
    var nameMap = { 6: "Full Word", 5: "Rare Word", 4: "Common Word", 3: "Small Word" };
    var rarityMap = { 6: "mythic", 5: "legendary", 4: "epic", 3: "uncommon" };
    badges.push({
      family: "word", name: nameMap[best.len], ep: epMap[best.len],
      desc: 'Your pull contains "' + best.word + '"', rarity: rarityMap[best.len]
    });
    for (var w = 1; w < words.length; w++) {
      if (words[w].word !== best.word) supporting.push(words[w].word);
    }
  }

  var counts = {};
  for (var c = 0; c < letters.length; c++) counts[letters[c]] = (counts[letters[c]] || 0) + 1;
  var maxCount = 0;
  for (var k in counts) maxCount = Math.max(maxCount, counts[k]);
  if (maxCount === 6) badges.push({ family: "repeat", name: "Sextuple", ep: 5000, desc: "All six letters identical", rarity: "mythic" });
  else if (maxCount === 5) badges.push({ family: "repeat", name: "Quintuple", ep: 800, desc: "Five matching letters", rarity: "legendary" });
  else if (maxCount === 4) badges.push({ family: "repeat", name: "Quadruple", ep: 200, desc: "Four matching letters", rarity: "epic" });
  else if (maxCount === 3) badges.push({ family: "repeat", name: "Triple", ep: 40, desc: "Three matching letters", rarity: "rare" });
  else if (maxCount === 2) badges.push({ family: "repeat", name: "Pair", ep: 5, desc: "A repeated letter", rarity: "common" });

  var run = longestRun(letters);
  if (run >= 6) badges.push({ family: "sequence", name: "Full Run", ep: 3000, desc: "All 6 letters run consecutively", rarity: "mythic" });
  else if (run >= 5) badges.push({ family: "sequence", name: "Long Run", ep: 400, desc: "5 letters run consecutively", rarity: "legendary" });
  else if (run >= 4) badges.push({ family: "sequence", name: "Short Run", ep: 80, desc: "4 letters run consecutively", rarity: "rare" });
  else if (run >= 3) badges.push({ family: "sequence", name: "Mini Run", ep: 15, desc: "3 letters run consecutively", rarity: "uncommon" });

  var rev = letters.slice().reverse().join("");
  if (seq === rev) {
    badges.push({ family: "symmetry", name: "Perfect Palindrome", ep: 1200, desc: "Reads the same forwards and backwards", rarity: "legendary" });
  } else if (letters[0] === letters[5]) {
    badges.push({ family: "symmetry", name: "Mirror Bookends", ep: 10, desc: "First and last letter match", rarity: "common" });
  } else if (letters[2] === letters[3]) {
    badges.push({ family: "symmetry", name: "Twin Core", ep: 8, desc: "Middle two letters match", rarity: "common" });
  }

  var vowelCount = 0;
  var pattern = "";
  for (var v = 0; v < letters.length; v++) {
    var isV = !!VOWELS[letters[v]];
    if (isV) vowelCount++;
    pattern += isV ? "V" : "C";
  }
  if (vowelCount === 6) badges.push({ family: "vowel", name: "All Vowels", ep: 600, desc: "Every letter is a vowel", rarity: "legendary" });
  else if (vowelCount === 0) badges.push({ family: "vowel", name: "No Vowels", ep: 150, desc: "Not a single vowel", rarity: "rare" });
  else if (pattern === "VCVCVC" || pattern === "CVCVCV") badges.push({ family: "vowel", name: "Perfect Alternation", ep: 100, desc: "Vowels and consonants alternate perfectly", rarity: "rare" });

  var kbLen = keyboardBestLen(seq);
  if (kbLen >= 4) badges.push({ family: "keyboard", name: "Keyboard Walk", ep: 250, desc: "4+ letters follow a keyboard row", rarity: "epic" });
  else if (kbLen === 3) badges.push({ family: "keyboard", name: "Keyboard Echo", ep: 30, desc: "3 letters follow a keyboard row", rarity: "uncommon" });

  badges.push({ family: "base", name: "Six Letters", ep: 1, desc: "Every roll earns this", rarity: "common" });

  var totalEP = 0;
  for (var b = 0; b < badges.length; b++) totalEP += badges[b].ep;

  var tier = "Trash";
  if (totalEP >= 3000) tier = "Mythic";
  else if (totalEP >= 1500) tier = "Legendary";
  else if (totalEP >= 500) tier = "Epic";
  else if (totalEP >= 150) tier = "Rare";
  else if (totalEP >= 50) tier = "Uncommon";
  else if (totalEP >= 10) tier = "Common";

  return { badges: badges, totalEP: totalEP, tier: tier, supporting: supporting };
}

var TIER_COLORS = {
  Trash: "#64748b", Common: "#94a3b8", Uncommon: "#4ade80",
  Rare: "#38bdf8", Epic: "#a78bfa", Legendary: "#facc15", Mythic: "#f87171"
};

function renderResult(letters, res) {
  var panel = document.getElementById("result");
  document.getElementById("resultTitle").textContent = letters.join("");
  var tag = document.getElementById("rarityTag");
  tag.textContent = res.tier;
  tag.style.background = TIER_COLORS[res.tier] + "22";
  tag.style.color = TIER_COLORS[res.tier];

  var list = document.getElementById("badgeList");
  list.innerHTML = "";
  for (var i = 0; i < res.badges.length; i++) {
    var b = res.badges[i];
    var li = document.createElement("li");
    li.className = "badge-item";
    li.innerHTML = "<div><span class='badge-name'>" + b.name + "</span>" +
      "<span class='badge-desc'>" + b.desc + "</span></div>" +
      "<span class='badge-ep'>+" + b.ep + " EP</span>";
    list.appendChild(li);
  }

  var sup = document.getElementById("supporting");
  sup.textContent = res.supporting.length ? ("Also spotted: " + res.supporting.join(", ")) : "";

  document.getElementById("totalEp").textContent = "Total: " + res.totalEP + " EP";
  panel.classList.add("show");
}

async function loadLeaderboard() {
  var res = await fetch("/api/leaderboard");
  var data = await res.json();
  var body = document.getElementById("lbBody");
  body.innerHTML = data.map(function (p, i) {
    return "<tr><td>" + (i + 1) + "</td><td>" + escapeHtml(p.name) + "</td><td>" +
      p.totalEP + "</td><td>" + p.rolls + "</td><td>" + p.bestEP + "</td></tr>";
  }).join("");
}

function escapeHtml(str) {
  return str.replace(/[&<>"']/g, function (c) {
    if (c === "&") return "&amp;";
    if (c === "<") return "&lt;";
    if (c === ">") return "&gt;";
    if (c === '"') return "&quot;";
    return "&#39;";
  });
}

function getCooldownRemaining() {
  var until = parseInt(localStorage.getItem("sixroll_next_roll") || "0", 10);
  return Math.max(0, until - Date.now());
}

function tickCooldown() {
  var unlimited = localStorage.getItem("sixroll_unlimited") === "1";
  var btn = document.getElementById("rollBtn");
  var text = document.getElementById("cooldownText");
  if (unlimited) {
    btn.disabled = false;
    text.textContent = "";
    return;
  }
  var remaining = getCooldownRemaining();
  if (remaining <= 0) {
    btn.disabled = false;
    text.textContent = "";
  } else {
    btn.disabled = true;
    var mins = Math.floor(remaining / 60000);
    var secs = Math.floor((remaining % 60000) / 1000);
    text.textContent = "Next roll in " + mins + ":" + (secs < 10 ? "0" : "") + secs;
  }
}
setInterval(tickCooldown, 1000);

document.getElementById("rollBtn").addEventListener("click", async function () {
  var name = getName();
  if (!name) {
    showToast("Enter a name first");
    nameInput.focus();
    return;
  }
  var btn = document.getElementById("rollBtn");
  btn.disabled = true;
  document.getElementById("result").classList.remove("show");

  var letters = [];
  for (var i = 0; i < 6; i++) letters.push(randLetter());

  for (var t = 0; t < 6; t++) {
    await revealTile(t, letters[t]);
  }

  var res = computeRoll(letters);
  renderResult(letters, res);

  var unlimited = localStorage.getItem("sixroll_unlimited") === "1";
  if (!unlimited) {
    localStorage.setItem("sixroll_next_roll", String(Date.now() + COOLDOWN_MS));
  }

  try {
    await fetch("/api/roll", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name: name, ep: res.totalEP })
    });
  } catch (e) {}

  await loadLeaderboard();
  tickCooldown();

  var settled = document.querySelectorAll(".tile.settled");
  for (var s = 0; s < settled.length; s++) settled[s].classList.remove("settled");
});

updateUnlimitedUI();
tickCooldown();
loadLeaderboard();
</script>
</body>
</html>`;

const KV_KEY = "players";
const MAX_PLAYERS = 200;

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    if (url.pathname === "/" && request.method === "GET") {
      return new Response(HTML_PAGE, { headers: { "content-type": "text/html;charset=UTF-8" } });
    }

    if (url.pathname === "/api/leaderboard" && request.method === "GET") {
      const players = await getPlayers(env);
      const top = players.slice().sort((a, b) => b.totalEP - a.totalEP).slice(0, 20);
      return json(top);
    }

    if (url.pathname === "/api/roll" && request.method === "POST") {
      let body;
      try {
        body = await request.json();
      } catch {
        return json({ error: "Invalid JSON" }, 400);
      }
      const name = String(body.name || "").trim().slice(0, 20);
      const ep = Number(body.ep);
      if (!name || !Number.isFinite(ep) || ep < 0) {
        return json({ error: "name and non-negative numeric ep required" }, 400);
      }

      const players = await getPlayers(env);
      const key = name.toLowerCase();
      let player = players.find((p) => p.name.toLowerCase() === key);
      if (!player) {
        player = { name, totalEP: 0, rolls: 0, bestEP: 0, ts: Date.now() };
        players.push(player);
      }
      player.totalEP += ep;
      player.rolls += 1;
      player.bestEP = Math.max(player.bestEP, ep);
      player.ts = Date.now();

      players.sort((a, b) => b.totalEP - a.totalEP);
      const trimmed = players.slice(0, MAX_PLAYERS);
      await env.PLAYERS.put(KV_KEY, JSON.stringify(trimmed));

      return json({ ok: true });
    }

    if (url.pathname === "/api/reset" && request.method === "POST") {
      await env.PLAYERS.put(KV_KEY, JSON.stringify([]));
      return json({ ok: true });
    }

    return new Response("Not found", { status: 404 });
  },
};

async function getPlayers(env) {
  const raw = await env.PLAYERS.get(KV_KEY);
  if (!raw) return [];
  try {
    return JSON.parse(raw);
  } catch {
    return [];
  }
}

function json(data, status = 200) {
  return new Response(JSON.stringify(data), { status, headers: { "content-type": "application/json" } });
}
